"""Source-closed SQL byte preflight. Nothing in this module grants authority."""
from contextlib import contextmanager, asynccontextmanager
from contextvars import ContextVar
from dataclasses import dataclass, field
import asyncio
import threading
from weakref import WeakValueDictionary
import json
import math
from types import MappingProxyType
from sqlalchemy import text
from sqlalchemy.dialects.sqlite import dialect
from src.memory.header_bounds import (HeaderBoundsError, HeaderReadBudget, MAX_ROWS,
    COMPOSITION_DESCRIPTORS, _COMPOSITION_MODELS)

_SCHEMA_TABLES = ('approval_requests', 'audio_consent_grants', 'audio_ingress_jobs', 'audit_events', 'calendar_event_bindings', 'calendar_prep_receipts', 'calendar_read_consents', 'calendar_reschedule_consents', 'forgejo_connections', 'github_followthrough_connections', 'goals', 'google_service_connections', 'governed_schedule_bindings', 'governed_schedule_occurrences', 'guardian_decision_packets', 'guardian_inbox_actions', 'guardian_inbox_dispositions', 'guardian_interventions', 'guardian_opportunities', 'guardian_routine_versions', 'guardian_routines', 'guardian_source_baselines', 'guardian_source_watches', 'inference_accounting_owners', 'inference_cost_reservations', 'mail_label_bindings', 'mail_message_bindings', 'mail_read_consents', 'mail_watch_states', 'memories', 'memory_edges', 'memory_entities', 'memory_episodes', 'memory_proposals', 'memory_snapshots', 'memory_sources', 'memory_tombstones', 'messages', 'model_capability_proofs', 'model_route_attempt_receipts', 'model_route_receipts', 'moltbook_connections', 'native_notification_delivery_attempts', 'native_notification_outbox', 'operator_continuity_credentials', 'operator_identities', 'operator_recovery_journals', 'operator_sessions', 'paired_edge_artifacts', 'procedure_v2_bindings', 'production_workflow_authority_states', 'production_workflow_fault_receipts', 'production_workflow_side_effect_receipts', 'programme_digest_receipts', 'programme_finding_actions', 'programme_follow_through', 'programme_notification_preferences', 'queued_insights', 'repo_repair_egress_consents', 'repo_repair_proposals', 'repo_repair_source_packets', 'runtime_composition_states', 'scheduled_job_runs', 'scheduled_jobs', 'screen_observations', 'secrets', 'session_todos', 'sessions', 'strategy_deltas', 'telegram_delivery_attempts', 'telegram_inbound_updates', 'telegram_task_callbacks', 'telegram_transport_outbox', 'telegram_transport_states', 'user_profiles', 'work_board_attempts', 'work_board_comments', 'work_board_decision_receipts', 'work_board_events', 'work_board_evidence_dependencies', 'work_board_handoffs', 'work_board_input_artifacts', 'work_board_links', 'work_board_proposals', 'work_board_review_intents', 'work_board_routine_bindings', 'work_board_tasks', 'workflow_artifact_reviews', 'workflow_run_states', 'workflow_step_states')
_NAMED_INDEXES = frozenset(('ix_approval_requests_action', 'ix_approval_requests_causation_id', 'ix_approval_requests_channel', 'ix_approval_requests_conversation_id', 'ix_approval_requests_correlation_id', 'ix_approval_requests_created_at', 'ix_approval_requests_device_id', 'ix_approval_requests_expires_at', 'ix_approval_requests_fingerprint', 'ix_approval_requests_operator_session_id', 'ix_approval_requests_owner_principal_id', 'ix_approval_requests_risk_level', 'ix_approval_requests_session_id', 'ix_approval_requests_status', 'ix_approval_requests_thread_id', 'ix_approval_requests_tool_name', 'ix_approval_requests_transport', 'ix_audio_consent_grants_boundary', 'ix_audio_consent_grants_created_at', 'ix_audio_consent_grants_expires_at', 'ix_audio_consent_grants_granted_at', 'ix_audio_consent_grants_operator_session_id', 'ix_audio_consent_grants_owner_principal_id', 'ix_audio_consent_grants_reference', 'ix_audio_consent_grants_revoked_at', 'ix_audio_consent_grants_state', 'ix_audio_consent_grants_updated_at', 'ix_audio_ingress_jobs_admission_operation_id', 'ix_audio_ingress_jobs_attachment_id', 'ix_audio_ingress_jobs_audio_payload_digest', 'ix_audio_ingress_jobs_captured_at', 'ix_audio_ingress_jobs_cleanup_status', 'ix_audio_ingress_jobs_confirmed_transcript_digest', 'ix_audio_ingress_jobs_created_at', 'ix_audio_ingress_jobs_error_code', 'ix_audio_ingress_jobs_message_id', 'ix_audio_ingress_jobs_operator_session_id', 'ix_audio_ingress_jobs_owner_principal_id', 'ix_audio_ingress_jobs_provider_status', 'ix_audio_ingress_jobs_raw_audio_retention_deadline', 'ix_audio_ingress_jobs_request_digest', 'ix_audio_ingress_jobs_request_id', 'ix_audio_ingress_jobs_requested_capability', 'ix_audio_ingress_jobs_result_digest', 'ix_audio_ingress_jobs_session_id', 'ix_audio_ingress_jobs_status', 'ix_audio_ingress_jobs_transcript_digest', 'ix_audio_ingress_jobs_transport_lease_id', 'ix_audio_ingress_jobs_transport_status', 'ix_audio_ingress_jobs_updated_at', 'ix_audit_events_actor', 'ix_audit_events_created_at', 'ix_audit_events_event_type', 'ix_audit_events_policy_mode', 'ix_audit_events_risk_level', 'ix_audit_events_session_id', 'ix_audit_events_tool_name', 'ix_calendar_event_bindings_calendar_list_revision', 'ix_calendar_event_bindings_connection_id', 'ix_calendar_event_bindings_connection_revision', 'ix_calendar_event_bindings_consent_id', 'ix_calendar_event_bindings_consent_revision', 'ix_calendar_event_bindings_created_at', 'ix_calendar_event_bindings_event_key', 'ix_calendar_event_bindings_event_revision', 'ix_calendar_event_bindings_fetched_at', 'ix_calendar_event_bindings_owner_event', 'ix_calendar_event_bindings_owner_principal_id', 'ix_calendar_event_bindings_owner_session_id', 'ix_calendar_event_bindings_provider_identity_digest', 'ix_calendar_event_bindings_revision', 'ix_calendar_event_bindings_snapshot_digest', 'ix_calendar_event_bindings_state', 'ix_calendar_event_bindings_updated_at', 'ix_calendar_prep_receipts_artifact_id', 'ix_calendar_prep_receipts_attempt_id', 'ix_calendar_prep_receipts_connection_id', 'ix_calendar_prep_receipts_connection_revision', 'ix_calendar_prep_receipts_consent_id', 'ix_calendar_prep_receipts_consent_revision', 'ix_calendar_prep_receipts_content_sha256', 'ix_calendar_prep_receipts_created_at', 'ix_calendar_prep_receipts_durable_job_id', 'ix_calendar_prep_receipts_event_binding_id', 'ix_calendar_prep_receipts_event_key', 'ix_calendar_prep_receipts_expires_at', 'ix_calendar_prep_receipts_failure_code', 'ix_calendar_prep_receipts_goal_id', 'ix_calendar_prep_receipts_goal_revision', 'ix_calendar_prep_receipts_memory_status', 'ix_calendar_prep_receipts_owner', 'ix_calendar_prep_receipts_owner_principal_id', 'ix_calendar_prep_receipts_owner_session_id', 'ix_calendar_prep_receipts_readback_id', 'ix_calendar_prep_receipts_status', 'ix_calendar_prep_receipts_task', 'ix_calendar_prep_receipts_task_id', 'ix_calendar_prep_receipts_updated_at', 'ix_calendar_read_consents_connection', 'ix_calendar_read_consents_connection_id', 'ix_calendar_read_consents_connection_revision', 'ix_calendar_read_consents_consent_digest', 'ix_calendar_read_consents_created_at', 'ix_calendar_read_consents_creation_request_digest', 'ix_calendar_read_consents_expires_at', 'ix_calendar_read_consents_goal_id', 'ix_calendar_read_consents_goal_revision', 'ix_calendar_read_consents_owner_principal_id', 'ix_calendar_read_consents_owner_session_id', 'ix_calendar_read_consents_owner_state', 'ix_calendar_read_consents_revision', 'ix_calendar_read_consents_state', 'ix_calendar_read_consents_updated_at', 'ix_calendar_reschedule_consents_event_binding_id', 'ix_calendar_reschedule_consents_expires_at', 'ix_calendar_reschedule_consents_goal_id', 'ix_calendar_reschedule_consents_original_root_session_id', 'ix_calendar_reschedule_consents_owner_principal_id', 'ix_calendar_reschedule_consents_read_connection_id', 'ix_calendar_reschedule_consents_state', 'ix_calendar_reschedule_consents_write_connection_id', 'ix_forgejo_connections_owner_principal_id', 'ix_forgejo_connections_owner_session_id', 'ix_github_followthrough_connections_active_fence', 'ix_github_followthrough_connections_active_job_id', 'ix_github_followthrough_connections_created_at', 'ix_github_followthrough_connections_mode', 'ix_github_followthrough_connections_owner_principal_id', 'ix_github_followthrough_connections_revision', 'ix_github_followthrough_connections_updated_at', 'ix_goals_domain', 'ix_goals_owner_principal_id', 'ix_goals_owner_session_id', 'ix_goals_parent_id', 'ix_goals_proactive_enabled', 'ix_goals_revision', 'ix_goals_status', 'ix_google_service_connections_created_at', 'ix_google_service_connections_credential_fingerprint', 'ix_google_service_connections_owner_principal_id', 'ix_google_service_connections_owner_session_id', 'ix_google_service_connections_owner_state', 'ix_google_service_connections_revision', 'ix_google_service_connections_revoke_idempotency_key', 'ix_google_service_connections_revoke_request_digest', 'ix_google_service_connections_scope_status', 'ix_google_service_connections_service', 'ix_google_service_connections_setup_request_digest', 'ix_google_service_connections_state', 'ix_google_service_connections_updated_at', 'ix_google_service_connections_vault_secret_key', 'ix_google_service_connections_verified_setup_job_id', 'ix_governed_schedule_bindings_action_digest', 'ix_governed_schedule_bindings_action_type', 'ix_governed_schedule_bindings_binding_revision', 'ix_governed_schedule_bindings_cadence_kind', 'ix_governed_schedule_bindings_capability_id', 'ix_governed_schedule_bindings_consent_digest', 'ix_governed_schedule_bindings_consent_kind', 'ix_governed_schedule_bindings_consent_revision', 'ix_governed_schedule_bindings_created_at', 'ix_governed_schedule_bindings_expires_at', 'ix_governed_schedule_bindings_goal_id', 'ix_governed_schedule_bindings_goal_revision', 'ix_governed_schedule_bindings_input_artifact_id', 'ix_governed_schedule_bindings_input_digest', 'ix_governed_schedule_bindings_last_slot_utc', 'ix_governed_schedule_bindings_owner_principal_id', 'ix_governed_schedule_bindings_owner_session_id', 'ix_governed_schedule_bindings_owner_state', 'ix_governed_schedule_bindings_read_consent_id', 'ix_governed_schedule_bindings_schedule_request_digest', 'ix_governed_schedule_bindings_scheduled_job_id', 'ix_governed_schedule_bindings_state', 'ix_governed_schedule_bindings_updated_at', 'ix_governed_schedule_occurrences_binding_id', 'ix_governed_schedule_occurrences_binding_revision', 'ix_governed_schedule_occurrences_binding_slot', 'ix_governed_schedule_occurrences_created_at', 'ix_governed_schedule_occurrences_durable_job_id', 'ix_governed_schedule_occurrences_idempotency_key', 'ix_governed_schedule_occurrences_lease_expires_at', 'ix_governed_schedule_occurrences_request_digest', 'ix_governed_schedule_occurrences_slot_utc', 'ix_governed_schedule_occurrences_state', 'ix_governed_schedule_occurrences_updated_at', 'ix_governed_schedule_occurrences_work_board_task_id', 'ix_guardian_decision_packets_approval_id', 'ix_guardian_decision_packets_created_at', 'ix_guardian_decision_packets_criteria_digest', 'ix_guardian_decision_packets_dossier_artifact_id', 'ix_guardian_decision_packets_dossier_sha256', 'ix_guardian_decision_packets_failure_code', 'ix_guardian_decision_packets_goal_id', 'ix_guardian_decision_packets_goal_revision', 'ix_guardian_decision_packets_inbox_pending_updated', 'ix_guardian_decision_packets_input_digest', 'ix_guardian_decision_packets_memory_status', 'ix_guardian_decision_packets_observed_checkpoint_sha256', 'ix_guardian_decision_packets_plan_revision', 'ix_guardian_decision_packets_run_identity', 'ix_guardian_decision_packets_source_watch_id', 'ix_guardian_decision_packets_status', 'ix_guardian_decision_packets_strategy_delta_id', 'ix_guardian_decision_packets_task_artifact_id', 'ix_guardian_decision_packets_task_sha256', 'ix_guardian_decision_packets_verification_status', 'ix_guardian_decision_packets_watch_id', 'ix_guardian_inbox_actions_action', 'ix_guardian_inbox_actions_created_at', 'ix_guardian_inbox_actions_idempotency_key', 'ix_guardian_inbox_actions_item', 'ix_guardian_inbox_actions_item_id', 'ix_guardian_inbox_actions_owner_principal_id', 'ix_guardian_inbox_actions_owner_session_id', 'ix_guardian_inbox_actions_payload_digest', 'ix_guardian_inbox_actions_task_id', 'ix_guardian_inbox_dispositions_created_at', 'ix_guardian_inbox_dispositions_expires_at', 'ix_guardian_inbox_dispositions_goal_id', 'ix_guardian_inbox_dispositions_goal_revision', 'ix_guardian_inbox_dispositions_last_action_receipt_id', 'ix_guardian_inbox_dispositions_owner_principal_id', 'ix_guardian_inbox_dispositions_owner_session_id', 'ix_guardian_inbox_dispositions_owner_state', 'ix_guardian_inbox_dispositions_plan_revision', 'ix_guardian_inbox_dispositions_revision', 'ix_guardian_inbox_dispositions_snoozed_until', 'ix_guardian_inbox_dispositions_source_digest', 'ix_guardian_inbox_dispositions_source_id', 'ix_guardian_inbox_dispositions_source_kind', 'ix_guardian_inbox_dispositions_state', 'ix_guardian_inbox_dispositions_task_id', 'ix_guardian_inbox_dispositions_updated_at', 'ix_guardian_inbox_dispositions_watch_id', 'ix_guardian_interventions_active_project', 'ix_guardian_interventions_created_at', 'ix_guardian_interventions_data_quality', 'ix_guardian_interventions_delivery_decision', 'ix_guardian_interventions_feedback_at', 'ix_guardian_interventions_feedback_type', 'ix_guardian_interventions_guardian_confidence', 'ix_guardian_interventions_interruption_mode', 'ix_guardian_interventions_intervention_type', 'ix_guardian_interventions_is_scheduled', 'ix_guardian_interventions_latest_outcome', 'ix_guardian_interventions_message_type', 'ix_guardian_interventions_notification_id', 'ix_guardian_interventions_opportunity_feedback', 'ix_guardian_interventions_policy_action', 'ix_guardian_interventions_session_id', 'ix_guardian_interventions_transport', 'ix_guardian_interventions_updated_at', 'ix_guardian_interventions_urgency', 'ix_guardian_interventions_user_state', 'ix_guardian_opportunity_owner_goal_created', 'ix_guardian_opportunity_status_created', 'ix_guardian_routine_versions_created_at', 'ix_guardian_routine_versions_installed_at', 'ix_guardian_routine_versions_installed_package_digest', 'ix_guardian_routine_versions_routine_id', 'ix_guardian_routine_versions_runbook_sha256', 'ix_guardian_routine_versions_version', 'ix_guardian_routine_versions_workflow_sha256', 'ix_guardian_routines_current_version', 'ix_guardian_routines_name', 'ix_guardian_routines_owner_principal_id', 'ix_guardian_routines_owner_session_id', 'ix_guardian_routines_revision', 'ix_guardian_routines_state', 'ix_guardian_source_baselines_baseline_sha256', 'ix_guardian_source_baselines_identity_digest', 'ix_guardian_source_baselines_last_error_code', 'ix_guardian_source_baselines_observed_at', 'ix_guardian_source_baselines_source_key', 'ix_guardian_source_baselines_state', 'ix_guardian_source_baselines_watch_id', 'ix_guardian_source_watches_active_job_fence', 'ix_guardian_source_watches_active_job_id', 'ix_guardian_source_watches_capability_id', 'ix_guardian_source_watches_capability_version', 'ix_guardian_source_watches_criteria_digest', 'ix_guardian_source_watches_goal_id', 'ix_guardian_source_watches_goal_revision', 'ix_guardian_source_watches_last_error_code', 'ix_guardian_source_watches_last_run_identity', 'ix_guardian_source_watches_last_status', 'ix_guardian_source_watches_owner_principal_id', 'ix_guardian_source_watches_owner_session_id', 'ix_guardian_source_watches_plan_revision', 'ix_guardian_source_watches_scheduled_job_id', 'ix_guardian_source_watches_source_set_digest', 'ix_guardian_source_watches_state', 'ix_guardian_source_watches_write_mode', 'ix_inference_cost_reservations_deployment_id', 'ix_inference_cost_reservations_goal_id', 'ix_inference_cost_reservations_job_id', 'ix_inference_cost_reservations_owner_group_lookup', 'ix_inference_cost_reservations_owner_id', 'ix_inference_cost_reservations_period_id', 'ix_inference_cost_reservations_sequence', 'ix_inference_cost_reservations_state', 'ix_mail_label_bindings_connection_id', 'ix_mail_label_bindings_connection_revision', 'ix_mail_label_bindings_created_at', 'ix_mail_label_bindings_owner_connection', 'ix_mail_label_bindings_owner_principal_id', 'ix_mail_label_bindings_owner_session_id', 'ix_mail_label_bindings_provider_label_digest', 'ix_mail_label_bindings_revision', 'ix_mail_label_bindings_state', 'ix_mail_label_bindings_updated_at', 'ix_mail_message_bindings_connection_id', 'ix_mail_message_bindings_connection_revision', 'ix_mail_message_bindings_created_at', 'ix_mail_message_bindings_fetched_at', 'ix_mail_message_bindings_message_key', 'ix_mail_message_bindings_message_revision', 'ix_mail_message_bindings_owner_principal_id', 'ix_mail_message_bindings_owner_session_id', 'ix_mail_message_bindings_owner_state', 'ix_mail_message_bindings_received_at', 'ix_mail_message_bindings_revision', 'ix_mail_message_bindings_source_consent_id', 'ix_mail_message_bindings_source_consent_revision', 'ix_mail_message_bindings_source_label_scope_digest', 'ix_mail_message_bindings_status', 'ix_mail_message_bindings_thread_key', 'ix_mail_message_bindings_updated_at', 'ix_mail_read_consents_connection', 'ix_mail_read_consents_connection_id', 'ix_mail_read_consents_connection_revision', 'ix_mail_read_consents_created_at', 'ix_mail_read_consents_creation_request_digest', 'ix_mail_read_consents_expires_at', 'ix_mail_read_consents_goal_id', 'ix_mail_read_consents_goal_revision', 'ix_mail_read_consents_max_messages', 'ix_mail_read_consents_model_digest', 'ix_mail_read_consents_model_egress_allowed', 'ix_mail_read_consents_model_reviewed_at', 'ix_mail_read_consents_model_revision', 'ix_mail_read_consents_owner_principal_id', 'ix_mail_read_consents_owner_session_id', 'ix_mail_read_consents_owner_state', 'ix_mail_read_consents_revision', 'ix_mail_read_consents_revoke_idempotency_key', 'ix_mail_read_consents_revoke_request_digest', 'ix_mail_read_consents_source_digest', 'ix_mail_read_consents_source_read_allowed', 'ix_mail_read_consents_source_reviewed_at', 'ix_mail_read_consents_source_revision', 'ix_mail_read_consents_state', 'ix_mail_read_consents_updated_at', 'ix_mail_read_consents_window_days', 'ix_mail_watch_states_baseline_complete', 'ix_mail_watch_states_connection_id', 'ix_mail_watch_states_connection_revision', 'ix_mail_watch_states_consent_id', 'ix_mail_watch_states_created_at', 'ix_mail_watch_states_goal_id', 'ix_mail_watch_states_goal_revision', 'ix_mail_watch_states_last_completed_occurrence_id', 'ix_mail_watch_states_last_observed_at', 'ix_mail_watch_states_list_fetched_at', 'ix_mail_watch_states_list_page_complete', 'ix_mail_watch_states_owner_principal_id', 'ix_mail_watch_states_owner_session_id', 'ix_mail_watch_states_owner_state', 'ix_mail_watch_states_revision', 'ix_mail_watch_states_seen_message_keys_digest', 'ix_mail_watch_states_skipped_coverage_reason', 'ix_mail_watch_states_source_consent_revision', 'ix_mail_watch_states_state', 'ix_mail_watch_states_updated_at', 'ix_mail_watch_states_window_end_utc', 'ix_mail_watch_states_window_start_utc', 'ix_memories_kind', 'ix_memories_kind_scope_key_unique', 'ix_memories_project_entity_id', 'ix_memories_scope_key', 'ix_memories_status', 'ix_memories_subject_entity_id', 'ix_memory_edges_edge_type', 'ix_memory_edges_from_memory_id', 'ix_memory_edges_to_memory_id', 'ix_memory_entities_canonical_key', 'ix_memory_entities_canonical_name', 'ix_memory_entities_entity_type', 'ix_memory_episodes_created_at', 'ix_memory_episodes_episode_type', 'ix_memory_episodes_observed_at', 'ix_memory_episodes_project_entity_id', 'ix_memory_episodes_session_id', 'ix_memory_episodes_source_message_id', 'ix_memory_episodes_source_role', 'ix_memory_episodes_source_tool_name', 'ix_memory_episodes_subject_entity_id', 'ix_memory_proposals_accepted_at', 'ix_memory_proposals_accepted_by_principal_id', 'ix_memory_proposals_accepted_by_session_id', 'ix_memory_proposals_accepted_memory_content_digest', 'ix_memory_proposals_accepted_memory_id', 'ix_memory_proposals_artifact_digest', 'ix_memory_proposals_artifact_ref', 'ix_memory_proposals_candidate_set_digest', 'ix_memory_proposals_capability_id', 'ix_memory_proposals_capability_version', 'ix_memory_proposals_corrects_memory_id', 'ix_memory_proposals_created_at', 'ix_memory_proposals_decision_effect', 'ix_memory_proposals_evidence_digest', 'ix_memory_proposals_exact_comparison', 'ix_memory_proposals_expires_at', 'ix_memory_proposals_goal_id', 'ix_memory_proposals_goal_revision', 'ix_memory_proposals_memory_kind', 'ix_memory_proposals_owner_principal_id', 'ix_memory_proposals_owner_session_id', 'ix_memory_proposals_preview_text_digest', 'ix_memory_proposals_privacy_state', 'ix_memory_proposals_proposal_job_id', 'ix_memory_proposals_provider_contact_count', 'ix_memory_proposals_provider_contact_started', 'ix_memory_proposals_provider_contact_state', 'ix_memory_proposals_readback_digest', 'ix_memory_proposals_reason_code', 'ix_memory_proposals_recovered_from_proposal_id', 'ix_memory_proposals_recovery_action', 'ix_memory_proposals_rejected_at', 'ix_memory_proposals_rejected_by_principal_id', 'ix_memory_proposals_rejected_by_session_id', 'ix_memory_proposals_request_binding_digest', 'ix_memory_proposals_request_idempotency_key', 'ix_memory_proposals_revision', 'ix_memory_proposals_rollback_at', 'ix_memory_proposals_rollback_by_principal_id', 'ix_memory_proposals_rollback_by_session_id', 'ix_memory_proposals_schema_version', 'ix_memory_proposals_source_attempt_fence', 'ix_memory_proposals_source_attempt_id', 'ix_memory_proposals_source_context_digest', 'ix_memory_proposals_source_task_id', 'ix_memory_proposals_source_task_revision', 'ix_memory_proposals_status', 'ix_memory_proposals_typed_input_digest', 'ix_memory_proposals_updated_at', 'ix_memory_proposals_workflow_run_id', 'ix_memory_proposals_workflow_run_revision', 'ix_memory_snapshots_canonical_tombstone_revision', 'ix_memory_snapshots_kind', 'ix_memory_sources_memory_id', 'ix_memory_sources_source_message_id', 'ix_memory_sources_source_session_id', 'ix_memory_sources_source_type', 'ix_memory_tombstones_actor', 'ix_memory_tombstones_created_at', 'ix_memory_tombstones_memory_id', 'ix_messages_causation_id', 'ix_messages_channel', 'ix_messages_conversation_id', 'ix_messages_correlation_id', 'ix_messages_device_id', 'ix_messages_operator_session_id', 'ix_messages_owner_principal_id', 'ix_messages_role', 'ix_messages_session_id', 'ix_messages_thread_id', 'ix_messages_transport', 'ix_model_capability_proofs_adapter', 'ix_model_capability_proofs_binding', 'ix_model_capability_proofs_capability', 'ix_model_capability_proofs_checked_at', 'ix_model_capability_proofs_created_at', 'ix_model_capability_proofs_endpoint_class', 'ix_model_capability_proofs_endpoint_digest', 'ix_model_capability_proofs_expires_at', 'ix_model_capability_proofs_model', 'ix_model_capability_proofs_outcome', 'ix_model_capability_proofs_profile_contract_hash', 'ix_model_capability_proofs_profile_id', 'ix_model_capability_proofs_profile_schema_version', 'ix_model_capability_proofs_proof_hash', 'ix_model_capability_proofs_receipt_hash', 'ix_model_capability_proofs_receipt_id', 'ix_model_route_attempt_receipts_attempt_id', 'ix_model_route_attempt_receipts_created_at', 'ix_model_route_attempt_receipts_endpoint_digest', 'ix_model_route_attempt_receipts_outcome', 'ix_model_route_attempt_receipts_profile_id', 'ix_model_route_attempt_receipts_route_receipt_id', 'ix_model_route_receipts_actual_profile_id', 'ix_model_route_receipts_created_at', 'ix_model_route_receipts_egress_class', 'ix_model_route_receipts_finished_at', 'ix_model_route_receipts_outcome', 'ix_model_route_receipts_receipt_hash', 'ix_model_route_receipts_receipt_id', 'ix_model_route_receipts_request_id', 'ix_model_route_receipts_route_decision_id', 'ix_model_route_receipts_runtime_path', 'ix_model_route_receipts_started_at', 'ix_model_route_receipts_workload', 'ix_model_route_receipts_workload_success', 'ix_moltbook_connections_owner_principal_id', 'ix_moltbook_connections_owner_session_id', 'ix_native_notification_delivery_attempts_attempt_index', 'ix_native_notification_delivery_attempts_error_code', 'ix_native_notification_delivery_attempts_fencing_token', 'ix_native_notification_delivery_attempts_finished_at', 'ix_native_notification_delivery_attempts_lease_owner', 'ix_native_notification_delivery_attempts_notification_id', 'ix_native_notification_delivery_attempts_started_at', 'ix_native_notification_delivery_attempts_status', 'ix_native_notification_outbox_attempt_count', 'ix_native_notification_outbox_budget_limit', 'ix_native_notification_outbox_budget_period_key', 'ix_native_notification_outbox_cancelled_at', 'ix_native_notification_outbox_causation_id', 'ix_native_notification_outbox_channel', 'ix_native_notification_outbox_continuation_mode', 'ix_native_notification_outbox_conversation_id', 'ix_native_notification_outbox_correlation_id', 'ix_native_notification_outbox_created_at', 'ix_native_notification_outbox_deadline_at', 'ix_native_notification_outbox_degraded_state', 'ix_native_notification_outbox_delivered_at', 'ix_native_notification_outbox_device_id', 'ix_native_notification_outbox_fencing_token', 'ix_native_notification_outbox_goal_id', 'ix_native_notification_outbox_goal_revision', 'ix_native_notification_outbox_idempotency_key', 'ix_native_notification_outbox_intervention_id', 'ix_native_notification_outbox_intervention_type', 'ix_native_notification_outbox_last_error', 'ix_native_notification_outbox_lease', 'ix_native_notification_outbox_lease_expires_at', 'ix_native_notification_outbox_lease_owner', 'ix_native_notification_outbox_max_attempts', 'ix_native_notification_outbox_operator_session_id', 'ix_native_notification_outbox_owner_principal_id', 'ix_native_notification_outbox_payload_digest', 'ix_native_notification_outbox_pending_order', 'ix_native_notification_outbox_session_id', 'ix_native_notification_outbox_status', 'ix_native_notification_outbox_surface', 'ix_native_notification_outbox_thread_id', 'ix_native_notification_outbox_thread_source', 'ix_native_notification_outbox_transport', 'ix_native_notification_outbox_updated_at', 'ix_native_notification_outbox_urgency', 'ix_operator_continuity_credentials_identity_id', 'ix_operator_continuity_credentials_kind', 'ix_operator_continuity_credentials_token_hash', 'ix_operator_recovery_journals_current_session_id', 'ix_operator_recovery_journals_identity_id', 'ix_operator_recovery_journals_state', 'ix_operator_sessions_absolute_expires_at', 'ix_operator_sessions_created_at', 'ix_operator_sessions_idle_expires_at', 'ix_operator_sessions_is_bearer_tombstone', 'ix_operator_sessions_last_seen_at', 'ix_operator_sessions_operator_identity_id', 'ix_operator_sessions_principal_id', 'ix_operator_sessions_replaced_by_id', 'ix_operator_sessions_replacement_state', 'ix_operator_sessions_revoked_at', 'ix_operator_sessions_token_hash', 'ix_paired_edge_artifacts_artifact_id', 'ix_paired_edge_artifacts_captured_at', 'ix_paired_edge_artifacts_content_hash', 'ix_paired_edge_artifacts_created_at', 'ix_paired_edge_artifacts_device_id', 'ix_paired_edge_artifacts_extension_id', 'ix_paired_edge_artifacts_owner_created', 'ix_paired_edge_artifacts_owner_principal_id', 'ix_paired_edge_artifacts_pairing_id', 'ix_paired_edge_artifacts_reference', 'ix_paired_edge_artifacts_request_id', 'ix_paired_edge_artifacts_sequence', 'ix_procedure_v2_bindings_created_at', 'ix_procedure_v2_bindings_deterministic_routine_id', 'ix_procedure_v2_bindings_idempotency_key', 'ix_procedure_v2_bindings_owner_principal_id', 'ix_procedure_v2_bindings_owner_session_id', 'ix_procedure_v2_bindings_preview_digest', 'ix_procedure_v2_bindings_preview_expires_at', 'ix_procedure_v2_bindings_recovery_reason', 'ix_procedure_v2_bindings_request_digest', 'ix_procedure_v2_bindings_revision', 'ix_procedure_v2_bindings_state', 'ix_procedure_v2_bindings_template_id', 'ix_procedure_v2_bindings_updated_at', 'ix_procedure_v2_bindings_version_id', 'ix_production_workflow_authority_states_blocked_replay_reason', 'ix_production_workflow_authority_states_created_at', 'ix_production_workflow_authority_states_lease_revision', 'ix_production_workflow_authority_states_resumable_step_state', 'ix_production_workflow_authority_states_run_identity', 'ix_production_workflow_authority_states_safe_replay_decision', 'ix_production_workflow_authority_states_scheduler_state_owner', 'ix_production_workflow_authority_states_side_effect_status', 'ix_production_workflow_authority_states_updated_at', 'ix_production_workflow_authority_states_worker_owner', 'ix_production_workflow_authority_states_workflow_lease_id', 'ix_production_workflow_authority_states_workflow_name', 'ix_production_workflow_authority_states_workflow_phase', 'ix_production_workflow_fault_receipts_campaign_window', 'ix_production_workflow_fault_receipts_created_at', 'ix_production_workflow_fault_receipts_fault_key', 'ix_production_workflow_fault_receipts_injection_method', 'ix_production_workflow_fault_receipts_operator_intervention_required', 'ix_production_workflow_fault_receipts_raw_receipt_handle', 'ix_production_workflow_fault_receipts_recovery_result', 'ix_production_workflow_fault_receipts_replay_decision', 'ix_production_workflow_fault_receipts_run_identity', 'ix_production_workflow_fault_receipts_updated_at', 'ix_production_workflow_side_effect_receipts_created_at', 'ix_production_workflow_side_effect_receipts_external_confirmation_state', 'ix_production_workflow_side_effect_receipts_idempotency_key', 'ix_production_workflow_side_effect_receipts_idempotency_scope', 'ix_production_workflow_side_effect_receipts_manual_repair_state', 'ix_production_workflow_side_effect_receipts_operator_replay_decision', 'ix_production_workflow_side_effect_receipts_reconciliation_id', 'ix_production_workflow_side_effect_receipts_reconciliation_outcome', 'ix_production_workflow_side_effect_receipts_redacted_receipt_handle', 'ix_production_workflow_side_effect_receipts_run_identity', 'ix_production_workflow_side_effect_receipts_side_effect_kind', 'ix_production_workflow_side_effect_receipts_updated_at', 'ix_programme_digest_receipts_local_date', 'ix_programme_digest_receipts_owner_identity_id', 'ix_programme_finding_actions_finding_id', 'ix_programme_finding_actions_local_date', 'ix_programme_finding_actions_owner_identity_id', 'ix_programme_follow_through_finding_id', 'ix_programme_follow_through_owner_identity_id', 'ix_queued_insights_budget_limit', 'ix_queued_insights_budget_period_key', 'ix_queued_insights_goal_id', 'ix_queued_insights_goal_revision', 'ix_queued_insights_intervention_id', 'ix_queued_insights_operator_session_id', 'ix_queued_insights_owner_principal_id', 'ix_queued_insights_session_id', 'ix_repo_repair_egress_consents_consent_digest', 'ix_repo_repair_egress_consents_created_at', 'ix_repo_repair_egress_consents_effective_profile_id', 'ix_repo_repair_egress_consents_effective_upstream', 'ix_repo_repair_egress_consents_expires_at', 'ix_repo_repair_egress_consents_goal_id', 'ix_repo_repair_egress_consents_goal_revision', 'ix_repo_repair_egress_consents_input_digest', 'ix_repo_repair_egress_consents_job_state', 'ix_repo_repair_egress_consents_owner_principal_id', 'ix_repo_repair_egress_consents_owner_session_id', 'ix_repo_repair_egress_consents_request_digest', 'ix_repo_repair_egress_consents_request_key', 'ix_repo_repair_egress_consents_revision', 'ix_repo_repair_egress_consents_runtime_path', 'ix_repo_repair_egress_consents_source_digest', 'ix_repo_repair_egress_consents_source_manifest_digest', 'ix_repo_repair_egress_consents_source_packet_id', 'ix_repo_repair_egress_consents_state', 'ix_repo_repair_egress_consents_updated_at', 'ix_repo_repair_egress_consents_work_board_attempt_id', 'ix_repo_repair_egress_consents_work_board_task_id', 'ix_repo_repair_egress_consents_workflow_run_id', 'ix_repo_repair_proposals_approval_fingerprint', 'ix_repo_repair_proposals_approval_id', 'ix_repo_repair_proposals_authority_digest', 'ix_repo_repair_proposals_base_snapshot_digest', 'ix_repo_repair_proposals_created_at', 'ix_repo_repair_proposals_expires_at', 'ix_repo_repair_proposals_goal_id', 'ix_repo_repair_proposals_goal_revision', 'ix_repo_repair_proposals_last_receipt_id', 'ix_repo_repair_proposals_model_output_digest', 'ix_repo_repair_proposals_model_profile_id', 'ix_repo_repair_proposals_model_request_digest', 'ix_repo_repair_proposals_model_response_artifact_id', 'ix_repo_repair_proposals_model_response_artifact_sha256', 'ix_repo_repair_proposals_model_runtime_path', 'ix_repo_repair_proposals_operation_key', 'ix_repo_repair_proposals_owner_principal_id', 'ix_repo_repair_proposals_owner_session_id', 'ix_repo_repair_proposals_owner_status', 'ix_repo_repair_proposals_patch_artifact_id', 'ix_repo_repair_proposals_patch_sha256', 'ix_repo_repair_proposals_repository_ref', 'ix_repo_repair_proposals_request_digest', 'ix_repo_repair_proposals_revision', 'ix_repo_repair_proposals_source_digest', 'ix_repo_repair_proposals_source_packet_id', 'ix_repo_repair_proposals_status', 'ix_repo_repair_proposals_updated_at', 'ix_repo_repair_proposals_work_board_attempt_id', 'ix_repo_repair_proposals_work_board_task_id', 'ix_repo_repair_proposals_workflow_run_id', 'ix_repo_repair_source_packets_artifact_id', 'ix_repo_repair_source_packets_artifact_sha256', 'ix_repo_repair_source_packets_base_snapshot_digest', 'ix_repo_repair_source_packets_created_at', 'ix_repo_repair_source_packets_goal_id', 'ix_repo_repair_source_packets_goal_revision', 'ix_repo_repair_source_packets_input_digest', 'ix_repo_repair_source_packets_owner_principal_id', 'ix_repo_repair_source_packets_owner_session_id', 'ix_repo_repair_source_packets_owner_state', 'ix_repo_repair_source_packets_repository_ref', 'ix_repo_repair_source_packets_revision', 'ix_repo_repair_source_packets_source_manifest_digest', 'ix_repo_repair_source_packets_state', 'ix_repo_repair_source_packets_updated_at', 'ix_repo_repair_source_packets_work_board_attempt_id', 'ix_repo_repair_source_packets_work_board_task_id', 'ix_repo_repair_source_packets_workflow_run_id', 'ix_scheduled_job_runs_action_type', 'ix_scheduled_job_runs_approval_id', 'ix_scheduled_job_runs_created_by_session_id', 'ix_scheduled_job_runs_finished_at', 'ix_scheduled_job_runs_outcome', 'ix_scheduled_job_runs_scheduled_job_id', 'ix_scheduled_job_runs_session_id', 'ix_scheduled_job_runs_started_at', 'ix_scheduled_job_runs_status', 'ix_scheduled_job_runs_trigger_type', 'ix_scheduled_jobs_action_type', 'ix_scheduled_jobs_created_by_session_id', 'ix_scheduled_jobs_enabled', 'ix_scheduled_jobs_last_approval_id', 'ix_scheduled_jobs_last_outcome', 'ix_scheduled_jobs_last_run_at', 'ix_scheduled_jobs_session_id', 'ix_scheduled_jobs_trigger_type', 'ix_screen_observations_activity_type', 'ix_screen_observations_app_name', 'ix_screen_observations_project', 'ix_screen_observations_timestamp', 'ix_secrets_key', 'ix_secrets_owner_principal_id', 'ix_secrets_revoked_at', 'ix_session_todos_completed', 'ix_session_todos_session_id', 'ix_session_todos_sort_order', 'ix_sessions_continuity_task_id', 'ix_sessions_owner_principal_id', 'ix_strategy_deltas_created_at', 'ix_strategy_deltas_field_name', 'ix_strategy_deltas_goal_id', 'ix_strategy_deltas_goal_revision_after', 'ix_strategy_deltas_goal_revision_before', 'ix_strategy_deltas_rollback_target_id', 'ix_strategy_deltas_scope', 'ix_strategy_deltas_source_event_id', 'ix_strategy_deltas_status', 'ix_telegram_delivery_attempts_attempt_index', 'ix_telegram_delivery_attempts_error_code', 'ix_telegram_delivery_attempts_fencing_token', 'ix_telegram_delivery_attempts_finished_at', 'ix_telegram_delivery_attempts_lease_owner', 'ix_telegram_delivery_attempts_outbox_id', 'ix_telegram_delivery_attempts_response_code', 'ix_telegram_delivery_attempts_started_at', 'ix_telegram_delivery_attempts_status', 'ix_telegram_inbound_updates_attachment_hash', 'ix_telegram_inbound_updates_attachment_id', 'ix_telegram_inbound_updates_attachment_quarantine_receipt_digest', 'ix_telegram_inbound_updates_canonical_message_id', 'ix_telegram_inbound_updates_chat_id', 'ix_telegram_inbound_updates_content_digest', 'ix_telegram_inbound_updates_created_at', 'ix_telegram_inbound_updates_idempotency_key', 'ix_telegram_inbound_updates_message_id', 'ix_telegram_inbound_updates_operator_id', 'ix_telegram_inbound_updates_operator_session_id', 'ix_telegram_inbound_updates_owner_principal_id', 'ix_telegram_inbound_updates_reason_code', 'ix_telegram_inbound_updates_request_digest', 'ix_telegram_inbound_updates_sequence', 'ix_telegram_inbound_updates_session_id', 'ix_telegram_inbound_updates_status', 'ix_telegram_inbound_updates_update_id', 'ix_telegram_task_callbacks_consumed_at', 'ix_telegram_task_callbacks_created_at', 'ix_telegram_task_callbacks_expires_at', 'ix_telegram_task_callbacks_nonce_digest', 'ix_telegram_task_callbacks_operator_session_id', 'ix_telegram_task_callbacks_outbox_id', 'ix_telegram_task_callbacks_owner_principal_id', 'ix_telegram_task_callbacks_pairing_id', 'ix_telegram_task_callbacks_query_id', 'ix_telegram_task_callbacks_status', 'ix_telegram_task_callbacks_task_id', 'ix_telegram_transport_outbox_attempt_count', 'ix_telegram_transport_outbox_cancelled_at', 'ix_telegram_transport_outbox_chat_id', 'ix_telegram_transport_outbox_content_digest', 'ix_telegram_transport_outbox_conversation_id', 'ix_telegram_transport_outbox_correlation_id', 'ix_telegram_transport_outbox_created_at', 'ix_telegram_transport_outbox_deadline_at', 'ix_telegram_transport_outbox_delivered_at', 'ix_telegram_transport_outbox_external_message_id', 'ix_telegram_transport_outbox_fencing_token', 'ix_telegram_transport_outbox_idempotency_key', 'ix_telegram_transport_outbox_kind', 'ix_telegram_transport_outbox_last_error', 'ix_telegram_transport_outbox_lease_expires_at', 'ix_telegram_transport_outbox_lease_owner', 'ix_telegram_transport_outbox_max_attempts', 'ix_telegram_transport_outbox_message_id', 'ix_telegram_transport_outbox_next_attempt_at', 'ix_telegram_transport_outbox_operator_session_id', 'ix_telegram_transport_outbox_owner_principal_id', 'ix_telegram_transport_outbox_payload_digest', 'ix_telegram_transport_outbox_response_code', 'ix_telegram_transport_outbox_session_id', 'ix_telegram_transport_outbox_status', 'ix_telegram_transport_outbox_thread_id', 'ix_telegram_transport_outbox_updated_at', 'ix_telegram_transport_states_chat_id', 'ix_telegram_transport_states_cursor', 'ix_telegram_transport_states_last_error', 'ix_telegram_transport_states_last_update_at', 'ix_telegram_transport_states_model_consent_expires_at', 'ix_telegram_transport_states_model_consent_reference', 'ix_telegram_transport_states_operator_id', 'ix_telegram_transport_states_operator_session_id', 'ix_telegram_transport_states_owner_principal_id', 'ix_telegram_transport_states_pairing_expires_at', 'ix_telegram_transport_states_pairing_id', 'ix_telegram_transport_states_pairing_state', 'ix_telegram_transport_states_revoked_at', 'ix_telegram_transport_states_sequence', 'ix_telegram_transport_states_token_fingerprint', 'ix_telegram_transport_states_token_secret_ref', 'ix_telegram_transport_states_transit_consent_expires_at', 'ix_telegram_transport_states_transit_consent_reference', 'ix_telegram_transport_states_updated_at', 'ix_work_board_attempts_cancel_requested_at', 'ix_work_board_attempts_created_at', 'ix_work_board_attempts_ended_at', 'ix_work_board_attempts_executor_id', 'ix_work_board_attempts_fencing_token', 'ix_work_board_attempts_heartbeat_at', 'ix_work_board_attempts_lease_expires_at', 'ix_work_board_attempts_lease_owner', 'ix_work_board_attempts_outcome', 'ix_work_board_attempts_started_at', 'ix_work_board_attempts_task_id', 'ix_work_board_attempts_task_revision_at_claim', 'ix_work_board_attempts_updated_at', 'ix_work_board_attempts_workflow_run_id', 'ix_work_board_comments_author_principal_id', 'ix_work_board_comments_author_session_id', 'ix_work_board_comments_created_at', 'ix_work_board_comments_owner_principal_id', 'ix_work_board_comments_owner_session_id', 'ix_work_board_comments_task_id', 'ix_work_board_decision_receipts_accepted_memory_content_digest', 'ix_work_board_decision_receipts_accepted_memory_id', 'ix_work_board_decision_receipts_admission_status', 'ix_work_board_decision_receipts_after_input_digest', 'ix_work_board_decision_receipts_after_selected_capability_id', 'ix_work_board_decision_receipts_before_input_digest', 'ix_work_board_decision_receipts_before_selected_capability_id', 'ix_work_board_decision_receipts_capability_id', 'ix_work_board_decision_receipts_capability_version', 'ix_work_board_decision_receipts_comparison_context_digest', 'ix_work_board_decision_receipts_confirmation_binding_digest', 'ix_work_board_decision_receipts_confirmed_at', 'ix_work_board_decision_receipts_confirmer_principal_id', 'ix_work_board_decision_receipts_confirmer_session_id', 'ix_work_board_decision_receipts_consumed_at', 'ix_work_board_decision_receipts_created_at', 'ix_work_board_decision_receipts_decision_status', 'ix_work_board_decision_receipts_exact_intent', 'ix_work_board_decision_receipts_goal_id', 'ix_work_board_decision_receipts_goal_revision', 'ix_work_board_decision_receipts_later_attempt_fence', 'ix_work_board_decision_receipts_later_attempt_id', 'ix_work_board_decision_receipts_later_task_id', 'ix_work_board_decision_receipts_later_task_revision', 'ix_work_board_decision_receipts_later_workflow_run_id', 'ix_work_board_decision_receipts_owner_principal_id', 'ix_work_board_decision_receipts_owner_session_id', 'ix_work_board_decision_receipts_receipt_binding_digest', 'ix_work_board_decision_receipts_receipt_stage', 'ix_work_board_decision_receipts_revision', 'ix_work_board_decision_receipts_schema_version', 'ix_work_board_decision_receipts_source_attempt_fence', 'ix_work_board_decision_receipts_source_attempt_id', 'ix_work_board_decision_receipts_source_baseline_receipt_id', 'ix_work_board_decision_receipts_source_context_digest', 'ix_work_board_decision_receipts_source_proposal_id', 'ix_work_board_decision_receipts_source_proposal_revision', 'ix_work_board_decision_receipts_source_task_id', 'ix_work_board_decision_receipts_source_task_revision', 'ix_work_board_decision_receipts_source_workflow_run_id', 'ix_work_board_decision_receipts_source_workflow_run_revision', 'ix_work_board_decision_receipts_task_intent_digest', 'ix_work_board_decision_receipts_typed_input_digest', 'ix_work_board_decision_receipts_updated_at', 'ix_work_board_events_actor_principal_id', 'ix_work_board_events_actor_session_id', 'ix_work_board_events_created_at', 'ix_work_board_events_kind', 'ix_work_board_events_owner_principal_id', 'ix_work_board_events_owner_session_id', 'ix_work_board_events_task_id', 'ix_work_board_evidence_dependencies_goal_id', 'ix_work_board_evidence_dependencies_owner_principal_id', 'ix_work_board_evidence_dependencies_owner_session_id', 'ix_work_board_evidence_dependencies_task_id', 'ix_work_board_evidence_owner_source', 'ix_work_board_handoffs_child_task_id', 'ix_work_board_handoffs_created_at', 'ix_work_board_handoffs_link_id', 'ix_work_board_handoffs_owner_principal_id', 'ix_work_board_handoffs_owner_session_id', 'ix_work_board_handoffs_parent_task_id', 'ix_work_board_handoffs_schema_version', 'ix_work_board_handoffs_source_attempt_id', 'ix_work_board_handoffs_source_task_revision', 'ix_work_board_handoffs_workflow_run_id', 'ix_work_board_input_artifacts_bound_task_id', 'ix_work_board_input_artifacts_bound_task_revision', 'ix_work_board_input_artifacts_capability_id', 'ix_work_board_input_artifacts_capability_version', 'ix_work_board_input_artifacts_consumed_at', 'ix_work_board_input_artifacts_created_at', 'ix_work_board_input_artifacts_expires_at', 'ix_work_board_input_artifacts_goal_id', 'ix_work_board_input_artifacts_goal_revision', 'ix_work_board_input_artifacts_idempotency_key', 'ix_work_board_input_artifacts_metadata_digest', 'ix_work_board_input_artifacts_owner_principal_id', 'ix_work_board_input_artifacts_owner_session_id', 'ix_work_board_input_artifacts_payload', 'ix_work_board_input_artifacts_payload_sha256', 'ix_work_board_input_artifacts_revision', 'ix_work_board_input_artifacts_state', 'ix_work_board_input_artifacts_state_expiry', 'ix_work_board_input_artifacts_typed_input_ref', 'ix_work_board_links_child_task_id', 'ix_work_board_links_created_at', 'ix_work_board_links_current_handoff_id', 'ix_work_board_links_owner_principal_id', 'ix_work_board_links_owner_session_id', 'ix_work_board_links_parent_task_id', 'ix_work_board_proposals_admission_job_id', 'ix_work_board_proposals_authority_digest', 'ix_work_board_proposals_capability_id', 'ix_work_board_proposals_capability_version', 'ix_work_board_proposals_created_at', 'ix_work_board_proposals_effect_id_digest', 'ix_work_board_proposals_expires_at', 'ix_work_board_proposals_goal_revision', 'ix_work_board_proposals_grant_revision', 'ix_work_board_proposals_idempotency_key', 'ix_work_board_proposals_input_digest', 'ix_work_board_proposals_kind', 'ix_work_board_proposals_owner_principal_id', 'ix_work_board_proposals_owner_session_id', 'ix_work_board_proposals_parent_revision', 'ix_work_board_proposals_parent_task_id', 'ix_work_board_proposals_proposal_digest', 'ix_work_board_proposals_provider_contact_started', 'ix_work_board_proposals_provider_contact_state', 'ix_work_board_proposals_request_digest', 'ix_work_board_proposals_revision', 'ix_work_board_proposals_route_id', 'ix_work_board_proposals_status', 'ix_work_board_review_intents_attempt_id', 'ix_work_board_review_intents_created_at', 'ix_work_board_review_intents_fencing_token', 'ix_work_board_review_intents_owner_principal_id', 'ix_work_board_review_intents_owner_session_id', 'ix_work_board_review_intents_request_digest', 'ix_work_board_review_intents_status', 'ix_work_board_review_intents_task_id', 'ix_work_board_review_intents_task_revision', 'ix_work_board_review_intents_workflow_run_id', 'ix_work_board_routine_bindings_action_task_id', 'ix_work_board_routine_bindings_created_at', 'ix_work_board_routine_bindings_deterministic_routine_id', 'ix_work_board_routine_bindings_idempotency_key', 'ix_work_board_routine_bindings_install_job_id', 'ix_work_board_routine_bindings_owner_principal_id', 'ix_work_board_routine_bindings_owner_session_id', 'ix_work_board_routine_bindings_preview_digest', 'ix_work_board_routine_bindings_revision', 'ix_work_board_routine_bindings_routine_id', 'ix_work_board_routine_bindings_source_task_id', 'ix_work_board_routine_bindings_state', 'ix_work_board_routine_bindings_updated_at', 'ix_work_board_tasks_archived_at', 'ix_work_board_tasks_assignee_id', 'ix_work_board_tasks_block_kind', 'ix_work_board_tasks_block_source_status', 'ix_work_board_tasks_capability_id', 'ix_work_board_tasks_completed_at', 'ix_work_board_tasks_created_at', 'ix_work_board_tasks_executor_id', 'ix_work_board_tasks_goal_id', 'ix_work_board_tasks_goal_revision', 'ix_work_board_tasks_idempotency_binding', 'ix_work_board_tasks_idempotency_key', 'ix_work_board_tasks_idempotency_payload_digest', 'ix_work_board_tasks_idempotency_scope', 'ix_work_board_tasks_input_artifact_id', 'ix_work_board_tasks_origin_session_id', 'ix_work_board_tasks_origin_thread_id', 'ix_work_board_tasks_owner_principal_id', 'ix_work_board_tasks_owner_session_id', 'ix_work_board_tasks_pipeline_operation_id', 'ix_work_board_tasks_pipeline_slot', 'ix_work_board_tasks_priority', 'ix_work_board_tasks_ready_order', 'ix_work_board_tasks_requires_review', 'ix_work_board_tasks_review_expires_at', 'ix_work_board_tasks_review_request_attempt_id', 'ix_work_board_tasks_review_request_digest', 'ix_work_board_tasks_review_request_fence', 'ix_work_board_tasks_review_request_revision', 'ix_work_board_tasks_review_requested_at', 'ix_work_board_tasks_reviewer_id', 'ix_work_board_tasks_scheduled_at', 'ix_work_board_tasks_status', 'ix_work_board_tasks_task_id', 'ix_work_board_tasks_task_revision', 'ix_work_board_tasks_typed_input_digest', 'ix_work_board_tasks_typed_input_ref', 'ix_work_board_tasks_updated_at', 'ix_workflow_artifact_reviews_approval_id', 'ix_workflow_artifact_reviews_artifact_path', 'ix_workflow_artifact_reviews_created_at', 'ix_workflow_artifact_reviews_decided_at', 'ix_workflow_artifact_reviews_owner', 'ix_workflow_artifact_reviews_parent_run_identity', 'ix_workflow_artifact_reviews_review_state', 'ix_workflow_artifact_reviews_reviewer', 'ix_workflow_artifact_reviews_root_run_identity', 'ix_workflow_artifact_reviews_run_identity', 'ix_workflow_artifact_reviews_updated_at', 'ix_workflow_artifact_reviews_workflow_name', 'ix_workflow_run_states_attempt_count', 'ix_workflow_run_states_authority_digest', 'ix_workflow_run_states_branch_kind', 'ix_workflow_run_states_budget_digest', 'ix_workflow_run_states_candidate_id', 'ix_workflow_run_states_capability_version', 'ix_workflow_run_states_conversation_id', 'ix_workflow_run_states_deadline_at', 'ix_workflow_run_states_failure_reason', 'ix_workflow_run_states_fencing_token', 'ix_workflow_run_states_finished_at', 'ix_workflow_run_states_goal_id', 'ix_workflow_run_states_goal_revision', 'ix_workflow_run_states_heartbeat_at', 'ix_workflow_run_states_idempotency_binding', 'ix_workflow_run_states_idempotency_key', 'ix_workflow_run_states_idempotency_scope', 'ix_workflow_run_states_input_digest', 'ix_workflow_run_states_job_kind', 'ix_workflow_run_states_last_completed_step_id', 'ix_workflow_run_states_lease_expires_at', 'ix_workflow_run_states_lease_owner', 'ix_workflow_run_states_max_attempts', 'ix_workflow_run_states_operator_session_id', 'ix_workflow_run_states_owner_kind', 'ix_workflow_run_states_owner_principal_id', 'ix_workflow_run_states_parent_fencing_token', 'ix_workflow_run_states_parent_job_id', 'ix_workflow_run_states_parent_run_identity', 'ix_workflow_run_states_plan_revision', 'ix_workflow_run_states_priority', 'ix_workflow_run_states_record_schema_version', 'ix_workflow_run_states_revision', 'ix_workflow_run_states_root_run_identity', 'ix_workflow_run_states_run_fingerprint', 'ix_workflow_run_states_run_identity', 'ix_workflow_run_states_selected_context_quota', 'ix_workflow_run_states_service_id', 'ix_workflow_run_states_session_id', 'ix_workflow_run_states_source_task', 'ix_workflow_run_states_started_at', 'ix_workflow_run_states_status', 'ix_workflow_run_states_tool_name', 'ix_workflow_run_states_updated_at', 'ix_workflow_run_states_workflow_name', 'ix_workflow_step_states_completed_at', 'ix_workflow_step_states_run_identity', 'ix_workflow_step_states_started_at', 'ix_workflow_step_states_status', 'ix_workflow_step_states_step_id', 'ix_workflow_step_states_step_index', 'ix_workflow_step_states_tool_name', 'ix_workflow_step_states_updated_at', 'ix_workflow_step_states_workflow_name', 'ux_audio_consent_grants_reference', 'ux_audio_ingress_jobs_request_id', 'ux_calendar_read_consents_creation_idempotency', 'ux_calendar_reschedule_active_grant', 'ux_forgejo_connection_owner', 'ux_github_followthrough_connections_owner', 'ux_guardian_decision_packets_watch_input', 'ux_guardian_inbox_actions_idempotency', 'ux_guardian_inbox_dispositions_source', 'ux_guardian_opportunity_owner_dedupe', 'ux_guardian_routine_versions_routine_version', 'ux_guardian_source_baselines_watch_source', 'ux_guardian_source_watches_scheduled_job', 'ux_mail_read_consents_creation_idempotency', 'ux_memory_proposals_owner_attempt_no_learning', 'ux_memory_proposals_owner_attempt_preview', 'ux_model_route_attempt_receipts_order', 'ux_moltbook_connection_owner', 'ux_native_notification_delivery_attempt_order', 'ux_operator_recovery_identity_key', 'ux_paired_edge_artifacts_pairing_request', 'ux_procedure_v2_bindings_deterministic_routine', 'ux_procedure_v2_bindings_idempotency', 'ux_programme_digest_owner_day', 'ux_programme_finding_action_owner_key', 'ux_programme_followthrough_owner_finding', 'ux_repo_repair_egress_consents_owner_request', 'ux_repo_repair_proposals_owner_operation', 'ux_repo_repair_source_packets_job_input', 'ux_strategy_deltas_source_event_id', 'ux_telegram_delivery_attempt_order', 'ux_work_board_attempts_active_task', 'ux_work_board_attempts_workflow_run', 'ux_work_board_decision_receipts_binding', 'ux_work_board_events_mutation_key', 'ux_work_board_handoffs_version', 'ux_work_board_input_artifacts_idempotency', 'ux_work_board_proposals_idempotency', 'ux_work_board_proposals_opportunity', 'ux_work_board_review_intents_binding', 'ux_work_board_routine_bindings_deterministic_routine', 'ux_work_board_routine_bindings_idempotency', 'ux_work_board_tasks_idempotency', 'ux_workflow_run_states_idempotency_binding'))
_AUTO_MAX = {'sessions': 1, 'messages': 1, 'audio_ingress_jobs': 1, 'audio_consent_grants': 1, 'session_todos': 1, 'scheduled_jobs': 1, 'scheduled_job_runs': 1, 'google_service_connections': 2, 'calendar_read_consents': 1, 'calendar_reschedule_consents': 2, 'mail_label_bindings': 2, 'mail_read_consents': 1, 'mail_message_bindings': 2, 'mail_watch_states': 2, 'calendar_event_bindings': 2, 'calendar_prep_receipts': 1, 'governed_schedule_bindings': 3, 'governed_schedule_occurrences': 2, 'guardian_source_watches': 1, 'guardian_source_baselines': 1, 'guardian_decision_packets': 1, 'github_followthrough_connections': 1, 'guardian_inbox_dispositions': 1, 'guardian_inbox_actions': 1, 'guardian_routines': 1, 'guardian_routine_versions': 1, 'work_board_routine_bindings': 1, 'procedure_v2_bindings': 1, 'work_board_tasks': 0, 'work_board_input_artifacts': 1, 'repo_repair_source_packets': 1, 'repo_repair_proposals': 1, 'repo_repair_egress_consents': 1, 'work_board_attempts': 1, 'work_board_review_intents': 1, 'work_board_links': 2, 'work_board_comments': 1, 'work_board_events': 0, 'work_board_evidence_dependencies': 2, 'work_board_proposals': 1, 'work_board_handoffs': 1, 'workflow_run_states': 1, 'runtime_composition_states': 1, 'inference_accounting_owners': 2, 'inference_cost_reservations': 1, 'workflow_step_states': 1, 'workflow_artifact_reviews': 1, 'production_workflow_authority_states': 1, 'production_workflow_fault_receipts': 1, 'production_workflow_side_effect_receipts': 1, 'memories': 1, 'memory_tombstones': 1, 'memory_entities': 1, 'memory_sources': 1, 'memory_proposals': 1, 'work_board_decision_receipts': 1, 'memory_snapshots': 1, 'memory_edges': 1, 'memory_episodes': 1, 'goals': 1, 'strategy_deltas': 1, 'user_profiles': 1, 'queued_insights': 1, 'guardian_interventions': 1, 'guardian_opportunities': 1, 'native_notification_outbox': 1, 'native_notification_delivery_attempts': 1, 'telegram_transport_states': 1, 'telegram_inbound_updates': 1, 'telegram_transport_outbox': 1, 'telegram_delivery_attempts': 1, 'telegram_task_callbacks': 1, 'screen_observations': 1, 'paired_edge_artifacts': 1, 'secrets': 1, 'audit_events': 1, 'model_capability_proofs': 1, 'model_route_receipts': 1, 'model_route_attempt_receipts': 1, 'approval_requests': 1, 'operator_sessions': 1, 'operator_identities': 1, 'programme_digest_receipts': 1, 'programme_follow_through': 1, 'programme_finding_actions': 1, 'programme_notification_preferences': 1, 'operator_continuity_credentials': 1, 'operator_recovery_journals': 1, 'moltbook_connections': 1, 'forgejo_connections': 1}
_SCHEMA_LIMIT = 1354
_SEAL = object()
_CURRENT = ContextVar("composition_header_bytes", default=None)


# Exact existing FTS5 auxiliary metadata, adopted separately from body tables.
_FTS_SQL = {'session_recall_fts': ('table', 'session_recall_fts', 'CREATE VIRTUAL TABLE session_recall_fts USING fts5(\n            entry_key UNINDEXED,\n            session_id UNINDEXED,\n            entry_type UNINDEXED,\n            source_label UNINDEXED,\n            text,\n            created_at UNINDEXED\n        )'), 'session_recall_fts_config': ('table', 'session_recall_fts_config', "CREATE TABLE 'session_recall_fts_config'(k PRIMARY KEY, v) WITHOUT ROWID"), 'session_recall_fts_content': ('table', 'session_recall_fts_content', "CREATE TABLE 'session_recall_fts_content'(id INTEGER PRIMARY KEY, c0, c1, c2, c3, c4, c5)"), 'session_recall_fts_data': ('table', 'session_recall_fts_data', "CREATE TABLE 'session_recall_fts_data'(id INTEGER PRIMARY KEY, block BLOB)"), 'session_recall_fts_docsize': ('table', 'session_recall_fts_docsize', "CREATE TABLE 'session_recall_fts_docsize'(id INTEGER PRIMARY KEY, sz BLOB)"), 'session_recall_fts_idx': ('table', 'session_recall_fts_idx', "CREATE TABLE 'session_recall_fts_idx'(segid, term, pgno, PRIMARY KEY(segid, term)) WITHOUT ROWID"), 'session_recall_episodes_ad': ('trigger', 'memory_episodes', "CREATE TRIGGER session_recall_episodes_ad\n        AFTER DELETE ON memory_episodes\n        BEGIN\n            DELETE FROM session_recall_fts WHERE entry_key = 'episode:' || OLD.id;\n        END"), 'session_recall_episodes_ai': ('trigger', 'memory_episodes', "CREATE TRIGGER session_recall_episodes_ai\n        AFTER INSERT ON memory_episodes\n        WHEN NEW.session_id IS NOT NULL AND NEW.episode_type != 'conversation'\n        BEGIN\n            INSERT INTO session_recall_fts (entry_key, session_id, entry_type, source_label, text, created_at)\n            VALUES (\n                'episode:' || NEW.id,\n                NEW.session_id,\n                'event',\n                COALESCE(NEW.episode_type, 'event'),\n                TRIM(COALESCE(NEW.summary, '') || CHAR(10) || COALESCE(NEW.content, '')),\n                COALESCE(NEW.observed_at, NEW.created_at)\n            );\n        END"), 'session_recall_episodes_au': ('trigger', 'memory_episodes', "CREATE TRIGGER session_recall_episodes_au\n        AFTER UPDATE OF session_id, episode_type, summary, content, observed_at, created_at ON memory_episodes\n        BEGIN\n            DELETE FROM session_recall_fts WHERE entry_key = 'episode:' || OLD.id;\n            INSERT INTO session_recall_fts (entry_key, session_id, entry_type, source_label, text, created_at)\n            SELECT\n                'episode:' || NEW.id,\n                NEW.session_id,\n                'event',\n                COALESCE(NEW.episode_type, 'event'),\n                TRIM(COALESCE(NEW.summary, '') || CHAR(10) || COALESCE(NEW.content, '')),\n                COALESCE(NEW.observed_at, NEW.created_at)\n            WHERE NEW.session_id IS NOT NULL AND NEW.episode_type != 'conversation';\n        END"), 'session_recall_messages_ad': ('trigger', 'messages', "CREATE TRIGGER session_recall_messages_ad\n        AFTER DELETE ON messages\n        BEGIN\n            DELETE FROM session_recall_fts WHERE entry_key = 'message:' || OLD.id;\n        END"), 'session_recall_messages_ai': ('trigger', 'messages', "CREATE TRIGGER session_recall_messages_ai\n        AFTER INSERT ON messages\n        WHEN NEW.role IN ('user', 'assistant')\n        BEGIN\n            INSERT INTO session_recall_fts (entry_key, session_id, entry_type, source_label, text, created_at)\n            VALUES ('message:' || NEW.id, NEW.session_id, 'message', NEW.role, COALESCE(NEW.content, ''), NEW.created_at);\n        END"), 'session_recall_messages_au': ('trigger', 'messages', "CREATE TRIGGER session_recall_messages_au\n        AFTER UPDATE OF role, content, session_id, created_at ON messages\n        BEGIN\n            DELETE FROM session_recall_fts WHERE entry_key = 'message:' || OLD.id;\n            INSERT INTO session_recall_fts (entry_key, session_id, entry_type, source_label, text, created_at)\n            SELECT 'message:' || NEW.id, NEW.session_id, 'message', NEW.role, COALESCE(NEW.content, ''), NEW.created_at\n            WHERE NEW.role IN ('user', 'assistant');\n        END"), 'session_recall_sessions_ad': ('trigger', 'sessions', "CREATE TRIGGER session_recall_sessions_ad\n        AFTER DELETE ON sessions\n        BEGIN\n            DELETE FROM session_recall_fts WHERE entry_key = 'session:' || OLD.id;\n        END"), 'session_recall_sessions_ai': ('trigger', 'sessions', "CREATE TRIGGER session_recall_sessions_ai\n        AFTER INSERT ON sessions\n        BEGIN\n            INSERT INTO session_recall_fts (entry_key, session_id, entry_type, source_label, text, created_at)\n            VALUES ('session:' || NEW.id, NEW.id, 'title', 'title', COALESCE(NEW.title, ''), COALESCE(NEW.updated_at, NEW.created_at));\n        END"), 'session_recall_sessions_au': ('trigger', 'sessions', "CREATE TRIGGER session_recall_sessions_au\n        AFTER UPDATE OF title, updated_at ON sessions\n        BEGIN\n            DELETE FROM session_recall_fts WHERE entry_key = 'session:' || OLD.id;\n            INSERT INTO session_recall_fts (entry_key, session_id, entry_type, source_label, text, created_at)\n            VALUES ('session:' || NEW.id, NEW.id, 'title', 'title', COALESCE(NEW.title, ''), COALESCE(NEW.updated_at, NEW.created_at));\n        END")}
_FTS_META = {'session_recall_fts': {'columns': [[0, 'entry_key', '', 0, None, 0, 0], [1, 'session_id', '', 0, None, 0, 0], [2, 'entry_type', '', 0, None, 0, 0], [3, 'source_label', '', 0, None, 0, 0], [4, 'text', '', 0, None, 0, 0], [5, 'created_at', '', 0, None, 0, 0], [6, 'session_recall_fts', '', 0, None, 0, 1], [7, 'rank', '', 0, None, 0, 1]], 'table': ['virtual', 8, 0, 0], 'indexes': [], 'index_columns': {}}, 'session_recall_fts_config': {'columns': [[0, 'k', '', 1, None, 1, 0], [1, 'v', '', 0, None, 0, 0]], 'table': ['shadow', 2, 1, 0], 'indexes': [[0, 'sqlite_autoindex_session_recall_fts_config_1', 1, 'pk', 0]], 'index_columns': {'sqlite_autoindex_session_recall_fts_config_1': [[0, 0, 'k', 0, 'BINARY', 1], [1, 1, 'v', 0, 'BINARY', 0]]}}, 'session_recall_fts_content': {'columns': [[0, 'id', 'INTEGER', 0, None, 1, 0], [1, 'c0', '', 0, None, 0, 0], [2, 'c1', '', 0, None, 0, 0], [3, 'c2', '', 0, None, 0, 0], [4, 'c3', '', 0, None, 0, 0], [5, 'c4', '', 0, None, 0, 0], [6, 'c5', '', 0, None, 0, 0]], 'table': ['shadow', 7, 0, 0], 'indexes': [], 'index_columns': {}}, 'session_recall_fts_data': {'columns': [[0, 'id', 'INTEGER', 0, None, 1, 0], [1, 'block', 'BLOB', 0, None, 0, 0]], 'table': ['shadow', 2, 0, 0], 'indexes': [], 'index_columns': {}}, 'session_recall_fts_docsize': {'columns': [[0, 'id', 'INTEGER', 0, None, 1, 0], [1, 'sz', 'BLOB', 0, None, 0, 0]], 'table': ['shadow', 2, 0, 0], 'indexes': [], 'index_columns': {}}, 'session_recall_fts_idx': {'columns': [[0, 'segid', '', 1, None, 1, 0], [1, 'term', '', 1, None, 2, 0], [2, 'pgno', '', 0, None, 0, 0]], 'table': ['shadow', 3, 1, 0], 'indexes': [[0, 'sqlite_autoindex_session_recall_fts_idx_1', 1, 'pk', 0]], 'index_columns': {'sqlite_autoindex_session_recall_fts_idx_1': [[0, 0, 'segid', 0, 'BINARY', 1], [1, 1, 'term', 0, 'BINARY', 1], [2, 2, 'pgno', 0, 'BINARY', 0]]}}}

def _sql(connection, query, parameters=()):
    return connection.exec_driver_sql(query, parameters) if hasattr(connection, "exec_driver_sql") else connection.execute(query, parameters)


_SNAPSHOT_SCOPE_SEAL = object()
_SNAPSHOT_SCOPES = WeakValueDictionary()
_SNAPSHOT_CERTIFICATES = WeakValueDictionary()
_CURRENT_SNAPSHOT_SCOPE = ContextVar("original_memory_snapshot_scope", default=None)


@dataclass(eq=False)
class _MemoryCurrentSnapshotScope:
    budget: object
    task: object
    thread: int
    invocation: object = field(default_factory=object)
    seal: object = field(default=_SNAPSHOT_SCOPE_SEAL, repr=False)
    certificates: dict = field(default_factory=dict, repr=False)
    live: bool = True


def _checked_current_snapshot_scope(budget):
    scope = _CURRENT_SNAPSHOT_SCOPE.get()
    if scope is None:
        return None
    if (type(scope) is not _MemoryCurrentSnapshotScope or scope.seal is not _SNAPSHOT_SCOPE_SEAL
            or _SNAPSHOT_SCOPES.get(id(scope)) is not scope or not scope.live
            or scope.budget is not budget or scope.task is not _snapshot_current_task()
            or scope.thread != threading.get_ident()):
        raise HeaderBoundsError("memory_snapshot_scope_unavailable")
    return scope


def _snapshot_current_task():
    try:
        return asyncio.current_task()
    except RuntimeError:
        return None


@contextmanager
def _memory_current_snapshot_scope(budget):
    """One lexical numeric operation; never a Source or writer permission."""
    if type(budget) is not HeaderReadBudget:
        raise HeaderBoundsError("header_request_bound")
    current = _checked_current_snapshot_scope(budget)
    if current is not None:
        yield current
        return
    scope = _MemoryCurrentSnapshotScope(budget, _snapshot_current_task(), threading.get_ident())
    _SNAPSHOT_SCOPES[id(scope)] = scope
    token = _CURRENT_SNAPSHOT_SCOPE.set(scope)
    try:
        yield scope
    finally:
        scope.live = False
        scope.certificates.clear()
        _SNAPSHOT_SCOPES.pop(id(scope), None)
        _CURRENT_SNAPSHOT_SCOPE.reset(token)


def _snapshot_schema_cookies(connection, budget):
    cookies = (_sql(connection, "PRAGMA main.schema_version").scalar_one(),
               _sql(connection, "PRAGMA temp.schema_version").scalar_one())
    if any(type(value) is not int or not 0 <= value < 2**31 for value in cookies):
        raise HeaderBoundsError("header_schema_cookie_unavailable")
    budget.debit(_metadata_cost(cookies), appearance=("schema-cookies",))
    return cookies


def _certify_current_memory_snapshot_on_connection(connection, budget):
    """Reuse only an original issued certificate for this exact live snapshot."""
    if type(budget) is not HeaderReadBudget:
        raise HeaderBoundsError("header_request_bound")
    scope = _checked_current_snapshot_scope(budget)
    if scope is None:
        return preflight_composition_superset(connection, budget)
    current = scope.certificates.get(connection)
    if current is not None:
        certificate, cookies = current
        if (type(certificate) is not CompositionHeaderCertificate
                or _SNAPSHOT_CERTIFICATES.get(id(certificate)) is not certificate
                or certificate.budget is not budget or certificate.connection is not connection):
            raise HeaderBoundsError("header_certificate_unavailable")
        try:
            _validate(connection, certificate)
        except HeaderBoundsError as error:
            if str(error) != "header_certificate_stale":
                raise
        else:
            if _snapshot_schema_cookies(connection, budget) == cookies:
                return certificate
    cookies = _snapshot_schema_cookies(connection, budget)
    certificate = preflight_composition_superset(connection, budget)
    if _snapshot_schema_cookies(connection, budget) != cookies:
        raise HeaderBoundsError("header_schema_cookie_changed")
    _validate(connection, certificate)
    _SNAPSHOT_CERTIFICATES[id(certificate)] = certificate
    scope.certificates[connection] = (certificate, cookies)
    return certificate


async def _certify_current_memory_snapshot(db, budget):
    return await (await db.connection()).run_sync(
        lambda connection: _certify_current_memory_snapshot_on_connection(connection, budget))


def _metadata_cost(rows):
    return len(json.dumps(rows, ensure_ascii=True, separators=(",", ":")).encode())


def _state(connection):
    if not connection.in_transaction():
        raise HeaderBoundsError("header_transaction_required")
    driver = connection.connection.driver_connection
    if not driver.in_transaction:
        raise HeaderBoundsError("header_sqlite_transaction_required")
    return connection.get_transaction(), driver, _sql(connection, "SELECT total_changes()").scalar_one()


def validate_descriptor_schema(connection, descriptor):
    model = _COMPOSITION_MODELS.get(descriptor.table)
    if model is None:
        # Original byte-only legacy descriptors use the same actual mapped table.
        from src.db import models
        model = next((c for c in vars(models).values() if isinstance(c, type)
                      and getattr(c, "__tablename__", None) == descriptor.table), None)
    if model is None:
        raise HeaderBoundsError("header_descriptor_unavailable")
    schema = list(_sql(connection, 'SELECT CASE WHEN octet_length(name)<=128 THEN name END,'
        'CASE WHEN octet_length(type)<=128 THEN type END,"notnull",pk,hidden '
        'FROM pragma_table_xinfo(?) LIMIT ?', (descriptor.table, len(descriptor.columns)+1)))
    expected = model.__table__
    if (len(schema) != len(descriptor.columns) or {r[0] for r in schema} != set(descriptor.columns)
            or any(r[4] != 0 or r[0] in {"rowid", "_rowid_", "oid"} for r in schema)):
        raise HeaderBoundsError("header_schema_changed")
    pk = tuple(r[0] for r in sorted(schema, key=lambda r:r[3]) if r[3])
    if pk != tuple(c.name for c in expected.primary_key.columns):
        raise HeaderBoundsError("header_schema_changed")
    for name, sql_type, notnull, _pk, _hidden in schema:
        column = expected.columns[name]
        if (sql_type != column.type.compile(dialect=dialect()).upper()
                or notnull != int(not column.nullable)):
            raise HeaderBoundsError("header_schema_changed")
    table = list(_sql(connection, 'SELECT wr FROM pragma_table_list WHERE schema="main" AND name=? LIMIT 2', (descriptor.table,)))
    if len(table) != 1 or table[0][0] != 0:
        raise HeaderBoundsError("header_schema_changed")
    if pk != (descriptor.key,):
        _validate_locator(connection, descriptor.table, descriptor.key, model)
    return _metadata_cost([list(r) for r in schema])


def _validate_locator(connection, table, column, model=None):
    model = model or _COMPOSITION_MODELS[table]
    source = [i for i in model.__table__.indexes if i.unique and tuple(c.name for c in i.columns)==(column,)]
    if len(source) != 1:
        raise HeaderBoundsError("header_locator_unsupported")
    name = source[0].name
    rows = list(_sql(connection, 'SELECT name,"unique",origin,partial FROM pragma_index_list(?) LIMIT ?',
                     (table, len(model.__table__.indexes)+len(model.__table__.constraints)+1)))
    match = [r for r in rows if r[0] == name]
    if len(match) != 1 or tuple(match[0][1:]) != (1,"c",0):
        raise HeaderBoundsError("header_locator_changed")
    parts = list(_sql(connection,'SELECT name,coll,desc,key,cid FROM pragma_index_xinfo(?) LIMIT 3',(name,)))
    keys = [r for r in parts if r[3]==1]
    if len(parts)!=2 or len(keys)!=1 or tuple(keys[0][:4])!=(column,"BINARY",0,1):
        raise HeaderBoundsError("header_locator_changed")
    return name


def _headers(connection, descriptor, identities):
    fields=['_rowid_']
    for name in descriptor.columns:
        fields += [f'typeof("{name}")', f'octet_length("{name}")',
                   f"CASE WHEN typeof(\"{name}\") IN ('integer','real') THEN \"{name}\" END"]
    result={}
    for key in identities:
        rows=list(_sql(connection,'SELECT '+','.join(fields)+f' FROM "{descriptor.table}" WHERE "{descriptor.key}"=? LIMIT 2',(key,)))
        if len(rows)!=1: raise HeaderBoundsError("header_row_unavailable")
        row=rows[0]
        skeleton=["native-composition-memory.v1",descriptor.table,key,[[n,None] for n in descriptor.columns]]
        cost=len(json.dumps(skeleton,ensure_ascii=True,separators=(",",":")).encode())+128
        for i,(kind,nullable) in enumerate(zip(descriptor.kinds,descriptor.nullable)):
            storage,size,number=row[1+i*3:4+i*3]
            if storage=="null":
                if not nullable:raise HeaderBoundsError("header_scalar_unavailable")
                continue
            if storage!=kind:raise HeaderBoundsError("header_scalar_type_unsupported")
            if kind=="text":cost+=6*size+2-4
            elif kind=="integer":
                if type(number) is not int or not -(2**63)<=number<2**63:raise HeaderBoundsError("header_scalar_unavailable")
                cost+=20-4
            else:
                if type(number) is not float or not math.isfinite(number):raise HeaderBoundsError("header_scalar_unavailable")
                cost+=64-4
        result[(descriptor.table,key)]=(row[0],cost)
    return result


def _discover(connection, descriptor, budget, key=None, tombstone=False, remaining=None):
    budget.debit(validate_descriptor_schema(connection,descriptor), appearance=("descriptor-schema", descriptor.table))
    if tombstone:
        name=_validate_locator(connection,descriptor.table,"memory_id")
        suffix=f' INDEXED BY "{name}" WHERE memory_id=?'
        parameters=(key,2)
    elif key is not None:
        suffix=f' WHERE "{descriptor.key}"=?'
        parameters=(key,2)
    else:
        suffix=''; parameters=((MAX_ROWS if remaining is None else remaining)+1,)
    column=descriptor.key
    rows=list(_sql(connection,f'SELECT _rowid_,typeof("{column}"),octet_length("{column}"),'
        f"CASE WHEN typeof(\"{column}\")='text' THEN CASE WHEN octet_length(\"{column}\") BETWEEN 1 AND 512 THEN \"{column}\" END END,"
        f"CASE WHEN typeof(\"{column}\")='integer' THEN \"{column}\" END FROM \"{descriptor.table}\""+suffix+' ORDER BY _rowid_ LIMIT ?',parameters))
    if len(rows)>(MAX_ROWS if remaining is None else remaining) and key is None:
        raise HeaderBoundsError("header_reference_bound")
    ids=[]
    for rowid,kind,_size,string,integer in rows:
        if descriptor.table=="work_board_events":
            if kind!="integer" or type(integer) is not int or integer!=rowid:raise HeaderBoundsError("header_rowid_unavailable")
            value=integer
        else:
            if kind!="text" or not string:raise HeaderBoundsError("header_scalar_unavailable")
            value=string
        ids.append(value)
    if len(ids)!=len(set(ids)):raise HeaderBoundsError("header_row_unavailable")
    for identity,row in zip(ids,rows):
        budget.resolve_future(descriptor,identity,row[0])
    budget.enroll((descriptor.table,r[0]) for r in rows)
    budget.debit(_metadata_cost([list(r) for r in rows]), appearance=("locator-metadata", descriptor.table, key, tombstone, tuple(ids)))
    return tuple(ids)


async def discover_rows(db, descriptor, budget):
    if type(budget) is not HeaderReadBudget or not any(descriptor is d for d in COMPOSITION_DESCRIPTORS.values()):
        raise HeaderBoundsError("header_descriptor_unavailable")
    return await (await db.connection()).run_sync(lambda c:_discover(c,descriptor,budget))


async def locate_exact_rows(db, descriptor, identity, budget):
    if type(identity) is not str or not 0<len(identity.encode())<=512:
        raise HeaderBoundsError("header_request_bound")
    if type(budget) is not HeaderReadBudget or not any(descriptor is d for d in COMPOSITION_DESCRIPTORS.values()):
        raise HeaderBoundsError("header_descriptor_unavailable")
    return await (await db.connection()).run_sync(lambda c:_discover(c,descriptor,budget,key=identity))


async def locate_tombstones(db, memory_id, budget):
    if type(memory_id) is not str or not 0<len(memory_id.encode())<=512 or type(budget) is not HeaderReadBudget:
        raise HeaderBoundsError("header_request_bound")
    return await (await db.connection()).run_sync(lambda c:_discover(c,COMPOSITION_DESCRIPTORS["memory_tombstones"],budget,key=memory_id,tombstone=True))


@dataclass(frozen=True,eq=False)
class CompositionHeaderCertificate:
    connection: object
    transaction: object
    driver: object
    changes: int
    rows: object
    budget: HeaderReadBudget
    seal: object
    issued_id: int=0


def _validate(connection,certificate):
    if type(certificate) is not CompositionHeaderCertificate or certificate.seal is not _SEAL or certificate.issued_id!=id(certificate) or certificate.connection is not connection:
        raise HeaderBoundsError("header_certificate_unavailable")
    if _state(connection)!=(certificate.transaction,certificate.driver,certificate.changes):
        raise HeaderBoundsError("header_certificate_stale")



def _validate_fts_metadata(connection,budget,objects):
    present={name for _rowid,_kind,name,_table in objects if name in _FTS_SQL}
    if not present:return  # An isolated pre-initialization/model-only schema.
    if present!=set(_FTS_SQL):raise HeaderBoundsError("header_fts_metadata_changed")
    for name,(kind,table,expected_sql) in _FTS_SQL.items():
        header=list(_sql(connection,"SELECT typeof(sql),octet_length(sql) FROM sqlite_schema WHERE name=? LIMIT 2",(name,)))
        if len(header)!=1 or tuple(header[0])!=("text",len(expected_sql.encode("utf-8"))):
            raise HeaderBoundsError("header_fts_metadata_changed")
        budget.debit(6*header[0][1]+2, appearance=("fts-sql", name))
        actual=_sql(connection,"SELECT sql FROM sqlite_schema WHERE name=? LIMIT 2",(name,)).scalar_one()
        if actual!=expected_sql:raise HeaderBoundsError("header_fts_metadata_changed")
    for name,expected in _FTS_META.items():
        columns=list(_sql(connection,'SELECT cid,CASE WHEN octet_length(name)<=128 THEN name END,'
            'CASE WHEN octet_length(type)<=128 THEN type END,"notnull",'
            'CASE WHEN dflt_value IS NULL THEN NULL WHEN octet_length(dflt_value)<=128 THEN dflt_value END,'
            'pk,hidden FROM pragma_table_xinfo(?) LIMIT ?',(name,len(expected["columns"])+1)))
        layout=list(_sql(connection,'SELECT type,ncol,wr,strict FROM pragma_table_list WHERE schema="main" AND name=? LIMIT 2',(name,)))
        indexes=list(_sql(connection,'SELECT seq,CASE WHEN octet_length(name)<=128 THEN name END,"unique",'
            'CASE WHEN octet_length(origin)<=2 THEN origin END,partial FROM pragma_index_list(?) LIMIT ?',(name,len(expected["indexes"])+1)))
        budget.debit(_metadata_cost([list(x) for x in (*columns,*layout,*indexes)]), appearance=("fts-schema", name))
        if ([list(x) for x in columns]!=expected["columns"] or [list(x) for x in layout]!=[expected["table"]]
                or [list(x) for x in indexes]!=expected["indexes"]):
            raise HeaderBoundsError("header_fts_metadata_changed")
        for index,parts in expected["index_columns"].items():
            actual=list(_sql(connection,'SELECT seqno,cid,CASE WHEN octet_length(name)<=128 THEN name END,'
                'desc,CASE WHEN octet_length(coll)<=128 THEN coll END,key FROM pragma_index_xinfo(?) LIMIT ?',(index,len(parts)+1)))
            budget.debit(_metadata_cost([list(x) for x in actual]), appearance=("fts-index", index))
            if [list(x) for x in actual]!=parts:raise HeaderBoundsError("header_fts_metadata_changed")


def preflight_composition_superset(connection,budget):
    if type(budget) is not HeaderReadBudget:raise HeaderBoundsError("header_request_bound")
    state=_state(connection)
    if tuple(map(int,_sql(connection,"SELECT sqlite_version()").scalar_one().split('.'))) < (3,43,0) or _sql(connection,"PRAGMA encoding").scalar_one()!="UTF-8":
        raise HeaderBoundsError("header_sqlite_version_unsupported")
    objects=list(_sql(connection,'SELECT rowid,CASE WHEN octet_length(type)<=7 THEN type END,'
        'CASE WHEN octet_length(name)<=128 THEN name END,CASE WHEN octet_length(tbl_name)<=128 THEN tbl_name END '
        'FROM sqlite_schema ORDER BY rowid LIMIT 1355'))
    if len(objects)>_SCHEMA_LIMIT:raise HeaderBoundsError("header_schema_object_bound")
    for _id,kind,name,table in objects:
        if kind=="table":valid=name==table and name in {*_SCHEMA_TABLES,"sqlite_sequence","alembic_version",*_FTS_META}
        elif kind=="index":
            valid=table in {*_SCHEMA_TABLES,"alembic_version"} and name in _NAMED_INDEXES
            prefix="sqlite_autoindex_"+str(table)+"_"
            if isinstance(name,str) and name.startswith(prefix):
                suffix=name[len(prefix):]
                valid=suffix.isascii() and suffix.isdecimal() and 1<=int(suffix)<=_AUTO_MAX.get(table,1 if table=="alembic_version" else 0)
        elif kind=="trigger":valid=(table=="operator_sessions" and name in {"operator_principal_required_insert","operator_principal_required_update"}) or (name in _FTS_SQL and _FTS_SQL[name][:2]==("trigger",table))
        else:valid=False
        if not valid:raise HeaderBoundsError("header_schema_object_unavailable")
    budget.debit(_metadata_cost([list(r) for r in objects]), appearance=("complete-schema",))
    _validate_fts_metadata(connection,budget,objects)
    allrows={}
    for descriptor in COMPOSITION_DESCRIPTORS.values():
        ids=_discover(connection,descriptor,budget,remaining=MAX_ROWS-len(allrows))
        rows=_headers(connection,descriptor,ids)
        budget.debit(sum(cost for _,cost in rows.values()), appearance=("complete-headers", descriptor.table, tuple(ids)))
        allrows.update(rows)
    if _state(connection)!=state:raise HeaderBoundsError("header_snapshot_changed")
    cert=CompositionHeaderCertificate(connection,*state,MappingProxyType(allrows),budget,_SEAL)
    object.__setattr__(cert,"issued_id",id(cert))
    return cert


async def certify_composition_superset(db,budget):
    return await (await db.connection()).run_sync(lambda c:preflight_composition_superset(c,budget))


async def validate_composition_certificate(db,certificate):
    await (await db.connection()).run_sync(lambda c:_validate(c,certificate))


@contextmanager
def snapshot_reads(certificate):
    _validate(certificate.connection,certificate)
    token=_CURRENT.set(certificate)
    try:yield
    finally:_CURRENT.reset(token)


@asynccontextmanager
async def snapshot_reads_async(db, certificate):
    """Validate on the real driver greenlet before an original async execute."""
    await validate_composition_certificate(db, certificate)
    token = _CURRENT.set(certificate)
    try:
        yield
    finally:
        _CURRENT.reset(token)


def charge_row(connection,table,key):
    certificate=_CURRENT.get()
    if certificate is None:return
    _validate(connection,certificate)
    if table=="work_board_events" and type(key) is str:
        key=int(key)
    row=certificate.rows.get((table,key))
    if row is None:raise HeaderBoundsError("header_row_unavailable")
    certificate.budget.debit(row[1], appearance=("body", table, key))


def charge_table(connection,table):
    """Debit the certified finite table before original full inventory reads."""
    certificate=_CURRENT.get()
    if certificate is None:return
    _validate(connection,certificate)
    if table not in COMPOSITION_DESCRIPTORS:raise HeaderBoundsError("header_descriptor_unavailable")
    identities = tuple(key for name, key in certificate.rows if name == table)
    certificate.budget.debit(sum(cost for (name,_key),(_rowid,cost) in certificate.rows.items() if name==table),
        appearance=("table-body", table, identities))


def current_budget():
    cert=_CURRENT.get()
    return cert.budget if cert is not None else None
