import { act, fireEvent, render, screen, waitFor, within } from "@testing-library/react";
import "@testing-library/jest-dom/vitest";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { CockpitHome } from "./CockpitHome";
import { homeFixture, sourceAt } from "../../lib/homeContinuation.fixture";
function response(payload: unknown, status = 200, cursor?: string) { return new Response(JSON.stringify(payload), { status, headers: cursor ? { "X-Continuation-Cursor": cursor } : {} }); }
describe("single-source Home continuation", () => {
  const fetch = vi.fn();
  beforeEach(() => { fetch.mockReset(); vi.stubGlobal("fetch", fetch); fetch.mockResolvedValue(response(homeFixture())); });
  afterEach(() => vi.unstubAllGlobals());
  it("loads once without programme/runtime/inbox fanout and presents pending work separately from outputs", async () => { render(<CockpitHome onOpenSection={vi.fn()} />); await screen.findByText(/Task task-1 · todo/); expect(fetch).toHaveBeenCalledTimes(1); expect(String(fetch.mock.calls[0][0])).toContain("/api/operator/continuation?limit=20"); expect(screen.getByRole("article", { name: "Prepared results" })).toHaveTextContent("result unknown"); expect(screen.getByText(/Historical method Unknown/)).toBeInTheDocument(); expect(screen.getByText(/rolled back metadata/)).toBeInTheDocument(); expect(screen.queryByText(/OpenRouter · governed/)).not.toBeInTheDocument(); });
  it("opens exact Goal, programme, Task, output, approval and original method targets", async () => { const open = vi.fn(); render(<CockpitHome onOpenSection={vi.fn()} onOpenContinuation={open} />); await screen.findByText(/Task task-1 · todo/); for (const kind of ["goal", "programme", "task", "output", "approval"]) { fireEvent.click(screen.getAllByRole("button", { name: new RegExp(`Inspect ${kind}$`) })[0]); expect(open.mock.calls[open.mock.calls.length - 1][0].kind).toBe(kind); } fireEvent.click(screen.getByRole("button", { name: "Inspect original method and rollback controls" })); expect(open.mock.calls[open.mock.calls.length - 1][0]).toEqual({ kind: "method", proposal_id: "proposal-1", version: "version-1", digest: "b".repeat(64) }); });
  it("retains the original rows and timestamp through failed refresh", async () => { render(<CockpitHome onOpenSection={vi.fn()} />); await screen.findByText(/Task task-1 · todo/); fetch.mockResolvedValue(response({ detail: { code: "source_unavailable" } }, 503)); fireEvent.click(screen.getByRole("button", { name: "Refresh Home" })); await screen.findByRole("status"); expect(screen.getByRole("status")).toHaveTextContent("Showing last confirmed metadata"); expect(screen.getByText(/Task task-1 · todo/)).toBeInTheDocument(); expect(screen.getByText(new RegExp(`Snapshot · ${sourceAt}`))).toHaveTextContent("last confirmed"); expect(fetch).toHaveBeenCalledTimes(2); });
  it("retains prior view on a partial source failure instead of claiming empty", async () => { render(<CockpitHome onOpenSection={vi.fn()} />); await screen.findByText(/Task task-1 · todo/); const partial = homeFixture(); partial.task_next_actions = { items: [], state: "degraded", source_as_of: null }; fetch.mockResolvedValue(response(partial)); fireEvent.click(screen.getByRole("button", { name: "Refresh Home" })); await screen.findByRole("status"); expect(screen.getByText(/Task task-1 · todo/)).toBeInTheDocument(); expect(screen.getByRole("status")).toHaveTextContent("source metadata is unavailable"); });
  it("keeps recovery and modules reachable on first-load failure without false zero counts", async () => { fetch.mockResolvedValue(response({ detail: { code: "home_unavailable" } }, 503)); const section = vi.fn(); render(<CockpitHome onOpenSection={section} />); await screen.findByRole("status"); expect(screen.getByRole("article", { name: "Next steps" })).toHaveTextContent("Metadata unavailable"); fireEvent.click(screen.getByRole("button", { name: "Open Connections" })); expect(section).toHaveBeenCalledWith("connections"); expect(screen.queryByText("No items on this page.")).not.toBeInTheDocument(); });
  it("uses original pagination cursor and requires explicit restart after stale anchor", async () => { fetch.mockResolvedValue(response(homeFixture(), 200, "original-cursor")); render(<CockpitHome onOpenSection={vi.fn()} />); await screen.findByRole("button", { name: "Next Home page" }); fetch.mockResolvedValue(response({ detail: { code: "continuation_stale" } }, 409)); fireEvent.click(screen.getByRole("button", { name: "Next Home page" })); await screen.findByRole("button", { name: "Restart Home snapshot" }); expect(String(fetch.mock.calls[1][0])).toContain("cursor=original-cursor"); expect(screen.getByRole("button", { name: "Next Home page" })).toBeDisabled(); fetch.mockResolvedValue(response(homeFixture())); fireEvent.click(screen.getByRole("button", { name: "Restart Home snapshot" })); await screen.findByRole("button", { name: "Refresh Home" }); expect(String(fetch.mock.calls[2][0])).not.toContain("cursor="); });
  it("returns keyboard focus to the exact row and retains snapshot when temporarily hidden", async () => { const props = { onOpenSection: vi.fn() }; const view = render(<CockpitHome {...props} />); await screen.findByText(/Task task-1 · todo/); view.rerender(<CockpitHome {...props} active={false} />); view.rerender(<CockpitHome {...props} active focusAttentionId="task_next_action:task-1:1" />); await waitFor(() => expect(screen.getByRole("button", { name: /Task task-1.*Inspect task/ })).toHaveFocus()); expect(fetch).toHaveBeenCalledTimes(1); });
  it("clears old-owner rows and discards delayed prior-owner responses", async () => { let resolve!: (v: Response) => void; fetch.mockImplementationOnce(() => new Promise<Response>(r => { resolve = r; })); const props = { onOpenSection: vi.fn() }; const view = render(<CockpitHome {...props} owner={{ principalId: "old", sessionId: "old-root" }} />); await waitFor(() => expect(fetch).toHaveBeenCalledTimes(1)); const current = homeFixture(); current.active_goals.items = []; current.active_goals.state = "empty"; fetch.mockResolvedValue(response(current)); view.rerender(<CockpitHome {...props} owner={{ principalId: "new", sessionId: "new-root" }} />); await screen.findByText(/Task task-1 · todo/); await act(async () => resolve(response(homeFixture()))); expect(within(screen.getByRole("article", { name: "Active goals" })).queryByText(/Goal goal-1/)).not.toBeInTheDocument(); expect(fetch).toHaveBeenCalledTimes(2); });
  it("keeps the exact keyboard order supplied within next steps and traverses actionable rows", async () => { render(<CockpitHome onOpenSection={vi.fn()} />); const task = await screen.findByRole("button", { name: /Task task-1.*Inspect task/ }); task.focus(); fireEvent.keyDown(task, { key: "ArrowDown" }); expect(screen.getByRole("button", { name: /Approval approval-1.*Inspect approval/ })).toHaveFocus(); fireEvent.keyDown(document.activeElement!, { key: "End" }); expect(screen.getByRole("button", { name: /Task task-result.*Inspect output/ })).toHaveFocus(); fireEvent.keyDown(document.activeElement!, { key: "Home" }); expect(task).toHaveFocus(); });
  it("rejects a continuation that changes its original as_of instead of silently renewing it", async () => { fetch.mockResolvedValue(response(homeFixture(), 200, "padded-cursor==")); render(<CockpitHome onOpenSection={vi.fn()} />); await screen.findByRole("button", { name: "Next Home page" }); const changed = homeFixture(); changed.as_of = "2026-10-09T10:03:00Z"; fetch.mockResolvedValue(response(changed, 200, "renewed==")); fireEvent.click(screen.getByRole("button", { name: "Next Home page" })); await screen.findByRole("button", { name: "Restart Home snapshot" }); expect(screen.getByText(new RegExp(`Snapshot · ${sourceAt}`))).toBeInTheDocument(); expect(String(fetch.mock.calls[1][0])).toContain("padded-cursor%3D%3D"); });

  it("keeps current Task metadata refresh usable while optional programme identity is confirmed blocked", async () => { const first = homeFixture(); first.programme_status = { items: [], state: "blocked", source_as_of: null }; fetch.mockResolvedValue(response(first)); const open = vi.fn(); render(<CockpitHome onOpenSection={vi.fn()} onOpenContinuation={open} />); await screen.findByText(/Task task-1 · todo/); const second = homeFixture(); second.programme_status = first.programme_status; const task = second.task_next_actions.items[0]; if (task.kind !== "task_next_action") throw Error(); task.task_revision = 2; task.target.task_revision = 2; fetch.mockResolvedValue(response(second)); fireEvent.click(screen.getByRole("button", { name: "Refresh Home" })); await waitFor(() => expect(fetch).toHaveBeenCalledTimes(2)); await waitFor(() => expect(screen.getByRole("button", { name: "Refresh Home" })).toBeEnabled()); fireEvent.click(screen.getByRole("button", { name: /Task task-1.*Inspect task/ })); expect(open.mock.calls[0][0].task_revision).toBe(2); expect(screen.getByRole("article", { name: "Programme progress" })).toHaveTextContent("Metadata blocked"); });

});
