import { fireEvent, render, screen, waitFor } from "@testing-library/react";
import { afterEach, beforeEach, expect, it, vi } from "vitest";
import { CockpitView } from "./CockpitView";
import { homeFixture } from "../../lib/homeContinuation.fixture";
import { useChatStore } from "../../stores/chatStore";
import { useCockpitLayoutStore } from "../../stores/cockpitLayoutStore";
import { usePanelLayoutStore } from "../../stores/panelLayoutStore";
import { useQuestStore } from "../../stores/questStore";
import { getDefaultPaneVisibility } from "./layouts";
const context = vi.hoisted(() => ({ session: { authenticated: true, principal_id: "operator", session_id: "root", absolute_expires_at: "2099-01-01T00:00:00Z", idle_expires_at: "2099-01-01T00:00:00Z" } }));
vi.mock("../auth/OperatorAuthGate", () => ({ useOptionalOperatorAuth: () => context }));
const board = vi.hoisted(() => ({ props: null as any }));
vi.mock("./WorkBoardPanel", () => ({ WorkBoardPanel: (props: any) => { board.props = props; return <section aria-label="Current Work inspector"><span>Focused {props.focusTaskId}</span><button onClick={props.onReturnAttention}>Return through existing attention owner</button></section>; } }));
const fetch = vi.fn();
beforeEach(() => {
  fetch.mockReset(); vi.stubGlobal("fetch", fetch);
  vi.stubGlobal("WebSocket", class { close() {} send() {} });
  useChatStore.setState({ messages: [], sessionId: "conversation", sessions: [], connectionStatus: "connected", isAgentBusy: false, onboardingCompleted: true });
  useQuestStore.setState({ goalTree: [], dashboard: { domains: {}, active_count: 0, completed_count: 0, total_count: 0 }, loading: false });
  usePanelLayoutStore.setState(usePanelLayoutStore.getInitialState(), true);
  useCockpitLayoutStore.setState({ activeSection: "home", activeLayoutId: "default", inspectorVisible: true, paneVisibility: getDefaultPaneVisibility("default"), savedPaneVisibility: { default: getDefaultPaneVisibility("default") } });
  fetch.mockImplementation(async (url: string) => new Response(JSON.stringify(String(url).includes("/api/operator/continuation?") ? homeFixture() : String(url).includes("/api/work-board/tasks?") ? { tasks: [], next_after: null, last_event_id: 0 } : String(url).includes("/api/work-board/events") ? { events: [], last_event_id: 0, gap: false } : String(url).endsWith("/api/auth/session") ? context.session : String(url).endsWith("/api/goals/tree") || String(url).endsWith("/api/sessions") || /\/api\/sessions\/[^/]+\/messages/.test(String(url)) ? [] : {})));
});
afterEach(() => vi.unstubAllGlobals());
it("connects Home's exact output to the existing Work owner and returns to its same page and keyboard row", async () => {
  render(<CockpitView onSend={() => {}} />);
  const output = await screen.findByRole("button", { name: /Task task-result.*Inspect output/ });
  fireEvent.click(output);
  await screen.findByRole("region", { name: "Current Work inspector" });
  expect(board.props.focusTaskId).toBe("task-result");
  expect(board.props.continuationOutput).toEqual({ kind: "output", task_id: "task-result", task_revision: 4, attempt_id: "attempt-1" });
  expect(board.props.attentionContext).toMatchObject({ taskId: "task-result", origin: "home", ownerKey: "operator:root", itemId: "prepared_output:task-result:attempt-1" });
  fireEvent.click(screen.getByRole("button", { name: "Return through existing attention owner" }));
  await waitFor(() => expect(output).toHaveFocus());
  expect(fetch.mock.calls.filter(([url]) => String(url).includes("/api/operator/continuation?"))).toHaveLength(1);
});
it("opens the exact canonical method owner rather than treating the currently displayed Task as its producer", async () => {
  const baseline = fetch.getMockImplementation();
  fetch.mockImplementation((url, init) => String(url).includes("/api/memory/task-methods/proposal-1") ? Promise.resolve(new Response(JSON.stringify({ detail: { code: "source_unavailable" } }), { status: 403 })) : baseline!(url, init));
  render(<CockpitView onSend={() => {}} />);
  fireEvent.click(await screen.findByRole("button", { name: "Inspect original method and rollback controls" }));
  await screen.findByRole("region", { name: "Original admitted method inspector" });
  await screen.findByText(/exact original method is unavailable/);
  expect(useCockpitLayoutStore.getState().activeSection).toBe("library");
  expect(fetch.mock.calls.some(([url]) => String(url).includes("/api/memory/task-methods/proposal-1"))).toBe(true);
  expect(fetch.mock.calls.some(([url]) => String(url).includes("/api/work-board/tasks/task-1"))).toBe(false);
  fireEvent.click(screen.getByRole("button", { name: "Return to Home snapshot" }));
  expect(useCockpitLayoutStore.getState().activeSection).toBe("home");
});
