import { fireEvent, render, screen, waitFor } from "@testing-library/react";
import { beforeEach, expect, it, vi } from "vitest";
import { apiFetch } from "../../lib/api";
import type { WorkBoardTask } from "../../types";
import { DocumentComparisonPanel } from "./DocumentComparisonPanel";
vi.mock("../../lib/api", () => ({ apiFetch: vi.fn() }));
const task = { task_id: "document-one", capability_id: "work.document-compare.v1", status: "done", task_revision: 5 } as WorkBoardTask;
const props = { task, ownerPrincipalId: "operator:one", ownerSessionId: "session-one" };
beforeEach(() => { vi.unstubAllGlobals(); vi.restoreAllMocks(); vi.mocked(apiFetch).mockReset(); sessionStorage.clear(); });
it("prepares literal verified CSV bytes and revokes replaced and unmounted Blob URLs", async () => {
  const csv = 'SKU,FORMULA\nPEN-01,"2 * 3.75"\n';
  vi.mocked(apiFetch).mockImplementation(async () => new Response(JSON.stringify({ text: csv })));
  const create = vi.fn().mockReturnValueOnce("blob:first").mockReturnValueOnce("blob:second");
  const revoke = vi.fn();
  vi.stubGlobal("URL", class extends URL { static createObjectURL = create; static revokeObjectURL = revoke; });
  const view = render(<DocumentComparisonPanel {...props} />);
  fireEvent.click(screen.getByRole("button", { name: "Prepare verified derived CSV" }));
  const anchor = await screen.findByRole("link", { name: "Save verified derived CSV" });
  expect(anchor).toHaveAttribute("href", "blob:first");
  expect(anchor).toHaveAttribute("download", "invoice-comparison.csv");
  expect(vi.mocked(apiFetch).mock.calls[0][0]).toContain(`/tasks/${task.task_id}/document-output/csv`);
  const blob = create.mock.calls[0][0] as Blob;
  const bytes = await new Promise<string>(resolve => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result)); reader.readAsText(blob); });
  expect(bytes).toBe(csv);
  fireEvent.click(screen.getByRole("button", { name: "Prepare verified derived CSV" }));
  await waitFor(() => expect(anchor).toHaveAttribute("href", "blob:second"));
  expect(revoke).toHaveBeenCalledWith("blob:first");
  view.unmount(); expect(revoke).toHaveBeenCalledWith("blob:second");
});
it("removes private output and revokes its Blob URL on owner, task, and logout changes", async () => {
  const create = vi.fn().mockReturnValue("blob:private"), revoke = vi.fn();
  vi.stubGlobal("URL", class extends URL { static createObjectURL = create; static revokeObjectURL = revoke; });
  vi.mocked(apiFetch).mockImplementation(async () => new Response(JSON.stringify({ text: "SKU,QTY\nPEN-01,2\n" })));
  const view = render(<DocumentComparisonPanel {...props} />);
  fireEvent.click(screen.getByRole("button", { name: "Prepare verified derived CSV" }));
  await screen.findByRole("link", { name: "Save verified derived CSV" });
  view.rerender(<DocumentComparisonPanel {...props} ownerSessionId="session-two" />);
  expect(screen.queryByRole("link", { name: "Save verified derived CSV" })).toBeNull();
  expect(revoke).toHaveBeenCalledWith("blob:private");
  fireEvent.click(screen.getByRole("button", { name: "Prepare verified derived CSV" }));
  await screen.findByRole("link", { name: "Save verified derived CSV" });
  view.rerender(<DocumentComparisonPanel {...props} task={{ ...task, task_id: "document-two" }} />);
  expect(screen.queryByRole("link", { name: "Save verified derived CSV" })).toBeNull();
  fireEvent.click(screen.getByRole("button", { name: "Prepare verified derived CSV" }));
  await screen.findByRole("link", { name: "Save verified derived CSV" });
  view.rerender(<DocumentComparisonPanel task={task} />);
  expect(screen.queryByRole("link", { name: "Save verified derived CSV" })).toBeNull();
});
it("renders report markup as literal text", async () => {
  vi.mocked(apiFetch).mockResolvedValue(new Response(JSON.stringify({ text: "<script>privateInvoice()</script>\nPEN-01: page 1, extraction line 3; CSV row 2" })));
  const view = render(<DocumentComparisonPanel {...props} />);
  fireEvent.click(screen.getByRole("button", { name: "Read verified cited report" }));
  await screen.findByText(/<script>privateInvoice/);
  expect(view.container.querySelector("script")).toBeNull();
});
