import { useEffect, useRef, useState } from "react";
import { makeMailIdempotencyKey } from "../../lib/mailApi";
import { actReply, listReplyProfiles, previewReply, readReply, recoverReplyOperation, listReplyRecoveryGoals } from "../../lib/mailReplyApi";
import type { ExactCommunicationApproval } from "../../lib/communications";
import type { ReplyJob, ReplyProfile } from "../../lib/mailReplyApi";

interface Props { taskId:string;messageRevision:string;ownerPrincipalId?:string|null;ownerSessionId?:string|null;goalId?:string|null;goalRevision?:number|null; onExactApproved?: (value: ExactCommunicationApproval | null) => void; onReadback?: (value: ReplyJob) => void; }
type Action="preview"|"decision"|"execute"|"cancel"|"observe";
interface Pending {version:1;action:Action;jobId:string|null;body:Record<string,unknown>;}
interface Stored {version:1;jobId:string|null;pending:Pending|null;}
const opaque=(x:unknown)=>typeof x==="string"&&/^[A-Za-z0-9_.:@+,-]{1,256}$/.test(x);
function decode(raw:string):Stored {if(raw.length>16384)throw Error();const s=JSON.parse(raw) as Stored;
  if(s.version!==1||(s.jobId!==null&&!opaque(s.jobId)))throw Error();if(s.pending){const p=s.pending;if(p.version!==1||!["preview","decision","execute","cancel","observe"].includes(p.action)||(p.jobId!==null&&!opaque(p.jobId))||!p.body||typeof p.body!=="object"||Array.isArray(p.body))throw Error();
    const allowed=new Set(["task_id","expected_message_revision","read_connection_id","expected_read_revision","send_connection_id","expected_send_revision","acknowledge_identity_source_read","acknowledge_exact_reply_send","request_uuid","decision","expected_digest","expected_revision","expected_original_revision","goal_id","goal_revision","acknowledge_readonly_recovery"]);
    if(Object.entries(p.body).some(([k,v])=>!allowed.has(k)||!(typeof v==="boolean"||Number.isSafeInteger(v)||opaque(v))))throw Error();}
  return s;}
export function MailReplySendPanel({taskId,messageRevision,ownerPrincipalId,ownerSessionId,goalId,onExactApproved,onReadback}:Props){
  const storageKey=ownerPrincipalId&&ownerSessionId?`seraph:mail-exact-reply:${encodeURIComponent(ownerPrincipalId)}:${encodeURIComponent(ownerSessionId)}:${encodeURIComponent(taskId)}`:null;
  const [saved,setSaved]=useState<Stored>({version:1,jobId:null,pending:null});const [job,setJob]=useState<ReplyJob|null>(null);const [aux,setAux]=useState<ReplyJob|null>(null);
  const [profiles,setProfiles]=useState<ReplyProfile[]>([]);const [readId,setReadId]=useState("");const [sendId,setSendId]=useState("");const [ack,setAck]=useState(false);const [recoverAck,setRecoverAck]=useState(false);
  const [recoveryGoals,setRecoveryGoals]=useState<{id:string;title:string;revision:number}[]>([]);const [recoveryId,setRecoveryId]=useState(goalId||"");
  const [busy,setBusy]=useState(false);const [error,setError]=useState<string|null>(null);const [storageError,setStorageError]=useState(false);
  const generation=useRef(0);const controller=useRef<AbortController|null>(null);
  useEffect(()=>{generation.current++;controller.current?.abort();controller.current=null;setBusy(false);setSaved({version:1,jobId:null,pending:null});setJob(null);setAux(null);setProfiles([]);setReadId("");setSendId("");setAck(false);setRecoverAck(false);setRecoveryGoals([]);setRecoveryId(goalId||"");setError(null);setStorageError(false);
    if(storageKey)try{const raw=sessionStorage.getItem(storageKey);if(raw)setSaved(decode(raw));}catch{setStorageError(true);}
    return()=>{generation.current++;controller.current?.abort();};},[storageKey]);
  function retain(value:Stored){if(!storageKey)throw Error();const raw=JSON.stringify(value);decode(raw);sessionStorage.setItem(storageKey,raw);if(sessionStorage.getItem(storageKey)!==raw)throw Error();setSaved(value);}
  async function run(action:(signal:AbortSignal,g:number)=>Promise<void>){if(!storageKey||busy||storageError)return;const g=generation.current;const c=new AbortController();controller.current=c;setBusy(true);setError(null);onExactApproved?.(null);if(onExactApproved)setJob(value=>value?{...value,preview:undefined}:value);try{await action(c.signal,g);}catch{if(g===generation.current)setError("The original action has an unconfirmed outcome. Inspect its canonical readback; no resend or replacement is authorized.");}finally{if(g===generation.current){setBusy(false);controller.current=null;}}}
  function accept(result:ReplyJob,pending:Pending|null,g:number){if(g!==generation.current)return;if(result.kind==="mail_reply_send_v1"&&(result.source_task_id!==taskId||(saved.jobId&&result.job_id!==saved.jobId)))throw Error();if(result.kind==="mail_reply_observation_v1"&&result.original_job_id!==saved.jobId)throw Error();if(pending?.body.request_uuid&&result.request_uuid!==pending.body.request_uuid)throw Error();if(pending?.action==="observe")setAux(result);else {if(pending?.jobId&&result.job_id!==pending.jobId)throw Error();setJob(result);}const original=saved.jobId||(pending?.action==="preview"?result.job_id:null);retain({version:1,jobId:original,pending:null});
    if(result.kind==="mail_reply_send_v1"){onReadback?.(result);const preview=result.preview;onExactApproved?.(result.status==="paused"&&preview?.approval_status==="approved"&&preview.expires_at*1000>Date.now()?{operation_id:result.job_id,exact_preview_digest:preview.decision_digest,approval_id:preview.approval_id,expires_at:preview.expires_at}:null);}
  }
  async function submit(pending:Pending,signal:AbortSignal,g:number){retain({version:1,jobId:saved.jobId,pending});const result=pending.action==="preview"?await previewReply(pending.body,signal):await actReply(pending.jobId!,pending.action,pending.body,signal);accept(result,pending,g);}
  async function inspect(signal:AbortSignal,g:number){let result:ReplyJob|null=null;
    if(saved.pending?.action==="preview"||saved.pending?.action==="observe")result=await recoverReplyOperation(saved.pending.action==="preview"?"mail_reply_send_v1":"mail_reply_observation_v1",String(saved.pending.body.request_uuid),signal);
    else if(saved.jobId)result=await readReply(saved.jobId,signal);
    if(g!==generation.current)return;if(!result){setError("No canonical receipt was found. Keep the exact original request for explicit retry; no automatic POST was made.");return;}
    const p=saved.pending;const matched=!p||p.action==="preview"||(p.action==="observe"&&result.status==="succeeded")||(p.action==="execute"&&result.status!=="paused")||(p.action==="decision"&&result.preview?.approval_status===p.body.decision)||(p.action==="cancel"&&result.cancel_requested&&(result as ReplyJob&{cancel_request_uuid?:string}).cancel_request_uuid===p.body.request_uuid);
    if(matched)accept(result,p,g);else {if(p?.action==="observe")setAux(result);else setJob(result);setError("The retained action is not proven applied. Keep its exact request; inspect again or explicitly retry it.");}}
  const read=profiles.find(p=>p.connection_id===readId);const send=profiles.find(p=>p.connection_id===sendId);
  const canPreview=!saved.jobId&&!saved.pending&&ack&&read&&send;
  const p=job?.preview;const recoveryGoal=recoveryGoals.find(g=>g.id===recoveryId);
  return <section className="mt-3 rounded border border-amber-500/30 p-3" aria-label="Exact Gmail reply send"><h3 className="font-semibold">Send one exact Gmail reply</h3><p className="text-[10px]">Uses the saved canonical draft, including its literal body. Local copy edits above are not sent. The server derives the original Subject, one recipient and real thread. No attachments, HTML, aliases or model calls.</p>
    <div className="flex gap-2 flex-wrap"><button className="cockpit-feedback-button" disabled={busy||!storageKey||storageError} onClick={()=>void run(async(signal,g)=>{const rows=await listReplyProfiles(signal);if(g!==generation.current)return;setProfiles(rows);setReadId(old=>old||rows.find(p=>p.service==="gmail_reply_read"&&p.state==="active")?.connection_id||"");setSendId(old=>old||rows.find(p=>p.service==="gmail_reply_send"&&p.state==="active")?.connection_id||"");})}>Load local reply profiles</button>
      {(saved.jobId||saved.pending)&&<button className="cockpit-feedback-button" disabled={busy||storageError} onClick={()=>void run(inspect)}>Inspect original reply readback</button>}</div>
    {!saved.jobId&&<div className="grid gap-2 mt-2"><label>Reply readonly identity profile<select value={readId} onChange={e=>setReadId(e.target.value)} disabled={busy||!!saved.pending}><option value="">Choose profile</option>{profiles.filter(p=>p.service==="gmail_reply_read"&&p.state==="active").map(p=><option key={p.connection_id} value={p.connection_id}>{p.label} · {p.scope_status}</option>)}</select></label>
      <label>Reply sender identity profile<select value={sendId} onChange={e=>setSendId(e.target.value)} disabled={busy||!!saved.pending}><option value="">Choose profile</option>{profiles.filter(p=>p.service==="gmail_reply_send"&&p.state==="active").map(p=><option key={p.connection_id} value={p.connection_id}>{p.label} · {p.scope_status}</option>)}</select></label>
      <label><input type="checkbox" checked={ack} onChange={e=>setAck(e.target.checked)} disabled={busy||!!saved.pending}/> Read this selected source and verified identity to prepare an exact reply preview (up to 5 contacts); separately consent to reviewing a send.</label>
      <button className="cockpit-feedback-button" disabled={busy||storageError||!canPreview} onClick={()=>void run((signal,g)=>submit({version:1,action:"preview",jobId:null,body:{task_id:taskId,expected_message_revision:messageRevision,read_connection_id:readId,expected_read_revision:read!.revision,send_connection_id:sendId,expected_send_revision:send!.revision,acknowledge_identity_source_read:true,acknowledge_exact_reply_send:true,request_uuid:makeMailIdempotencyKey("reply-preview")}},signal,g))}>Prepare exact send preview</button></div>}
    {saved.pending&&<div className="mt-2" role="status">Original {saved.pending.action} action retained. Reload never sends or approves. <button className="cockpit-feedback-button" disabled={busy||storageError} onClick={()=>void run((signal,g)=>submit(saved.pending!,signal,g))}>Retry exact original action</button></div>}
    {job&&<p className="mt-2" role="status">Original send: {job.outcome==="verified_in_sender_sent_mailbox"?"Verified in sender's Sent mailbox; recipient delivery is not proven.":job.status==="unknown_external_effect"?"Unknown; no resend.":job.status} · {job.contacts_spent}/14 contacts · deadline {job.deadline_at} · no learning{job.cancel_requested?" · cancellation requested; inspect actual cleanup separately":""}</p>}
    {p&&<div className="mt-2 grid gap-1"><div>Verified sender: {p.sender}</div><div>One recipient (incoming Reply-To is untrusted): {p.recipient}</div><div>Original Subject: {p.subject}</div><div>Preview expires: {new Date(p.expires_at*1000).toISOString()} · approval: {p.approval_status} · no attachments</div><pre className="whitespace-pre-wrap text-[11px] border p-2">{p.body}</pre>
      {job?.status==="paused"&&!saved.pending&&p.approval_status==="pending"&&<><button className="cockpit-feedback-button" disabled={busy||storageError} onClick={()=>void run((signal,g)=>submit({version:1,action:"decision",jobId:job.job_id,body:{decision:"approved",expected_digest:p.decision_digest}},signal,g))}>Approve these exact bytes and recipient</button><button className="cockpit-feedback-button" disabled={busy||storageError} onClick={()=>void run((signal,g)=>submit({version:1,action:"decision",jobId:job.job_id,body:{decision:"denied",expected_digest:p.decision_digest}},signal,g))}>Deny exact reply</button></>}
      {job?.status==="paused"&&!saved.pending&&p.approval_status==="approved"&&<button className="cockpit-feedback-button" disabled={busy||storageError} onClick={()=>void run((signal,g)=>submit({version:1,action:"execute",jobId:job.job_id,body:{}},signal,g))}>Send approved reply once (up to 9 contacts)</button>}
    </div>}
    {job&&!saved.pending&&["paused","running","blocked"].includes(job.status)&&<button className="cockpit-feedback-button" disabled={busy||storageError} onClick={()=>void run((signal,g)=>submit({version:1,action:"cancel",jobId:job.job_id,body:{expected_revision:job.revision,request_uuid:makeMailIdempotencyKey("reply-cancel")}},signal,g))}>Cancel original reply</button>}
    {job?.status==="unknown_external_effect"&&!saved.pending&&<div className="grid gap-2 mt-2"><p>Reconcile through a separate current finite readonly Goal. Original send deadline, Goal and liability remain unchanged. Original live operator session is required.</p><label>Recovery readonly profile<select value={readId} onChange={e=>setReadId(e.target.value)}><option value="">Choose profile</option>{profiles.filter(p=>p.service==="gmail_reply_read"&&p.state==="active").map(p=><option key={p.connection_id} value={p.connection_id}>{p.label}</option>)}</select></label><button className="cockpit-feedback-button" disabled={busy} onClick={()=>void run(async(signal,g)=>{const rows=await listReplyRecoveryGoals(signal);if(g===generation.current)setRecoveryGoals(rows);})}>Load current readonly RecoveryGoals</button><label>Separate finite RecoveryGoal<select value={recoveryId} onChange={e=>setRecoveryId(e.target.value)}><option value="">Choose active finite Goal</option>{recoveryGoals.map(g=><option key={g.id} value={g.id}>{g.title} · revision {g.revision}</option>)}</select></label><label><input type="checkbox" checked={recoverAck} onChange={e=>setRecoverAck(e.target.checked)}/> Authorize one readonly Sent observation, at most 9 contacts; no send token or resend.</label>
      <button className="cockpit-feedback-button" disabled={busy||storageError||!read||!recoveryGoal||!recoverAck||!job.transport_quiescent} onClick={()=>void run((signal,g)=>submit({version:1,action:"observe",jobId:job.job_id,body:{expected_original_revision:job.revision,read_connection_id:readId,expected_read_revision:read!.revision,goal_id:recoveryGoal!.id,goal_revision:recoveryGoal!.revision,acknowledge_readonly_recovery:true,request_uuid:makeMailIdempotencyKey("reply-observation")}},signal,g))}>Reconcile original send with readonly Goal</button></div>}
    {aux&&<p role="status">Separate readonly observation: {aux.outcome} · original send remains Unknown · no learning.</p>}{job?.observations?.map(o=><p key={o.auxiliary_job_id}>Read-only history: {o.outcome} · original write outcome unchanged.</p>)}
    {storageError&&<p role="alert">Private recovery storage is corrupt or unavailable. Actions are blocked; do not create a replacement send.</p>}{error&&<p role="alert">{error}</p>}
  </section>;
}
