"""Provider-neutral model-fabric contracts and fail-closed route selection."""

from .contracts import (
    MODEL_FABRIC_SCHEMA_VERSION,
    EndpointClass,
    InferenceRequestContext,
    InferenceRequirements,
    InferenceWorkload,
    ModelCapability,
    NoCompliantModelRouteError,
    ModelRouteCandidate,
    ModelRouteProof,
    ProviderProfile,
    RouteDecision,
    RouteRejection,
    default_egress_for_workload,
    bind_final_inference_payload,
    finalized_openai_compatible_body,
    transport_model_for_provider,
    credential_ref_allowed,
    has_inline_secret_options,
    transport_endpoint,
)
from .selector import (
    SUPPORTED_PROVIDER_KINDS,
    candidate_from_profile,
    classify_endpoint,
    preflight_candidate,
    provider_family_exclusion_reason,
    profile_exclusion_reason,
    select_route,
)
from .execution import RouteReceiptHooks, execute_streaming, run_preflighted_adapter
from .proofs import build_model_route_proof, canonical_proof_hash, proof_is_fresh, validate_model_route_proof
from .receipts import CostEstimate, ReceiptPersistenceResult, RouteAttemptReceipt, RouteReceipt, TokenUsage
from .repository import ModelFabricRepository, ProofPersistenceResult, model_fabric_repository
from .probe import CapabilityProbeObservation, CapabilityProbeResult, run_capability_probe
from .hooks import PersistedRouteReceiptHooks, RouteReceiptSession, persist_denied_route

__all__ = [
    "MODEL_FABRIC_SCHEMA_VERSION",
    "EndpointClass",
    "InferenceRequestContext",
    "InferenceRequirements",
    "InferenceWorkload",
    "ModelCapability",
    "NoCompliantModelRouteError",
    "ModelRouteCandidate",
    "ModelRouteProof",
    "ProviderProfile",
    "RouteDecision",
    "RouteRejection",
    "default_egress_for_workload",
    "bind_final_inference_payload",
    "finalized_openai_compatible_body",
    "transport_model_for_provider",
    "credential_ref_allowed",
    "has_inline_secret_options",
    "transport_endpoint",
    "candidate_from_profile",
    "classify_endpoint",
    "preflight_candidate",
    "select_route",
    "SUPPORTED_PROVIDER_KINDS",
    "provider_family_exclusion_reason",
    "profile_exclusion_reason",
    "RouteReceiptHooks",
    "execute_streaming",
    "run_preflighted_adapter",
    "build_model_route_proof",
    "canonical_proof_hash",
    "proof_is_fresh",
    "validate_model_route_proof",
    "CostEstimate",
    "ReceiptPersistenceResult",
    "RouteAttemptReceipt",
    "RouteReceipt",
    "TokenUsage",
    "ModelFabricRepository",
    "ProofPersistenceResult",
    "model_fabric_repository",
    "CapabilityProbeObservation",
    "CapabilityProbeResult",
    "run_capability_probe",
    "PersistedRouteReceiptHooks",
    "RouteReceiptSession",
    "persist_denied_route",
]
