import { useEffect, useRef, useState } from "react";
import { makeMailIdempotencyKey } from "../../lib/mailApi";
import { importReplyProfile, listReplyProfiles, pairReplyProfiles, recoverReplyProfile, recoverReplyOperation, replyScopes, revokeReplyProfile } from "../../lib/mailReplyApi";
import type { ReplyProfile, ReplyRole } from "../../lib/mailReplyApi";

interface Props { ownerPrincipalId?: string|null; ownerSessionId?: string|null; goals: {id:string;title:string;revision:number}[]; }
export function MailReplyProfiles({ownerPrincipalId,ownerSessionId,goals}:Props) {
  const key=ownerPrincipalId&&ownerSessionId ? `seraph:mail-reply-profile:${encodeURIComponent(ownerPrincipalId)}:${encodeURIComponent(ownerSessionId)}` : null;
  const [profiles,setProfiles]=useState<ReplyProfile[]>([]); const [role,setRole]=useState<ReplyRole>("gmail_reply_read");
  const [label,setLabel]=useState("");const [clientId,setClientId]=useState("");const [secret,setSecret]=useState("");const [token,setToken]=useState("");
  const [ack,setAck]=useState(false);const [goalId,setGoalId]=useState("");const [readId,setReadId]=useState("");const [sendId,setSendId]=useState("");
  const [pairPending,setPairPending]=useState<Record<string,unknown>|null>(null);const [pending,setPending]=useState<string|null>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState<string|null>(null);const [outcome,setOutcome]=useState<string|null>(null);
  const generation=useRef(0);const controller=useRef<AbortController|null>(null);
  useEffect(()=>{generation.current++;controller.current?.abort();setBusy(false);setProfiles([]);setPending(null);setPairPending(null);setError(null);setOutcome(null);setToken("");setSecret("");setClientId("");setAck(false);setReadId("");setSendId("");
    if(key)try{const saved=sessionStorage.getItem(key);if(saved){if(!/^[A-Za-z0-9_.:@+,-]{1,256}$/.test(saved))throw Error();setPending(saved);}const pairRaw=sessionStorage.getItem(key+":identity");if(pairRaw){if(pairRaw.length>4096)throw Error();const parsed=JSON.parse(pairRaw);const keys=["read_connection_id","expected_read_revision","send_connection_id","expected_send_revision","goal_id","goal_revision","acknowledge_identity_read","request_uuid"];if(Object.keys(parsed).length!==keys.length||keys.some(k=>!(k in parsed))||Object.values(parsed).some(v=>!(typeof v==="boolean"||Number.isSafeInteger(v)||(typeof v==="string"&&/^[A-Za-z0-9_.:@+,-]{1,256}$/.test(v)))))throw Error();setPairPending(parsed);}}catch{setError("Private setup recovery storage is unavailable. Imports are blocked.");}
    return()=>{generation.current++;controller.current?.abort();};},[key]);
  async function run(action:(signal:AbortSignal)=>Promise<void>){if(!key||busy)return;const g=generation.current;const c=new AbortController();controller.current=c;setBusy(true);setError(null);try{await action(c.signal);}catch{if(g===generation.current)setError("The operation is unconfirmed. Inspect canonical readback before another action.");}finally{if(g===generation.current){setBusy(false);controller.current=null;}}}
  async function refresh(signal:AbortSignal){const g=generation.current;const rows=await listReplyProfiles(signal);if(g!==generation.current)return;setProfiles(rows);setReadId(old=>old||rows.find(p=>p.service==="gmail_reply_read"&&p.state==="active")?.connection_id||"");setSendId(old=>old||rows.find(p=>p.service==="gmail_reply_send"&&p.state==="active")?.connection_id||"");}
  async function save(signal:AbortSignal){if(!key||!ack||pending)return;const requestKey=makeMailIdempotencyKey("reply-profile");sessionStorage.setItem(key,requestKey);if(sessionStorage.getItem(key)!==requestKey)throw Error();setPending(requestKey);const g=generation.current;
    try{const profile=await importReplyProfile({service:role,label,client_id:clientId,client_secret:secret||null,refresh_token:token,declared_scopes:replyScopes(role),acknowledge_separate_identity_profile:true,idempotency_key:requestKey},signal);
      if(g===generation.current){sessionStorage.removeItem(key);setPending(null);setProfiles(old=>[profile,...old.filter(x=>x.connection_id!==profile.connection_id)]);setOutcome("Imported locally. This grants no provider contact or send permission.");}}
    finally{if(g===generation.current){setToken("");setSecret("");setClientId("");setAck(false);}}}
  async function reconcile(signal:AbortSignal){if(!key||!pending)return;const g=generation.current;const profile=await recoverReplyProfile(pending,signal);if(g!==generation.current)return;if(profile?.state==="active"){sessionStorage.removeItem(key);setPending(null);setProfiles(old=>[profile,...old.filter(x=>x.connection_id!==profile.connection_id)]);setOutcome("Original import confirmed by local readback.");}else setOutcome("Import is absent or unfinished. Keep the original setup key; no credentials were replayed.");}
  const goal=goals.find(x=>x.id===goalId);const read=profiles.find(x=>x.connection_id===readId);const send=profiles.find(x=>x.connection_id===sendId);
  return <section className="rounded border border-cyan-500/30 p-3 my-3" aria-label="Exact Gmail reply profiles"><h3 className="font-semibold">Exact Gmail reply profiles</h3><p className="text-[10px]">Import separate readonly + identity and send + identity grants. Every refresh must prove the exact selected scopes. Legacy Mail source access remains separate. No background account checks.</p>
    <button className="cockpit-feedback-button" disabled={busy||!key} onClick={()=>void run(refresh)}>Refresh reply profile metadata</button>
    <form className="grid gap-2 mt-2" onSubmit={e=>{e.preventDefault();void run(save);}}>
      <label>Reply profile role<select aria-label="Reply profile role" value={role} onChange={e=>setRole(e.target.value as ReplyRole)} disabled={busy||!!pending}><option value="gmail_reply_read">Readonly + identity</option><option value="gmail_reply_send">Send + identity</option></select></label>
      <div className="text-[10px]">Exact scopes: {replyScopes(role).join(" · ")}</div>
      <label>Reply profile label<input className="cockpit-input w-full" value={label} maxLength={200} onChange={e=>setLabel(e.target.value)} disabled={busy||!!pending}/></label>
      <label>Reply client ID<input className="cockpit-input w-full" value={clientId} maxLength={4096} autoComplete="off" onChange={e=>setClientId(e.target.value)} disabled={busy||!!pending}/></label>
      <label>Reply client secret (optional)<input className="cockpit-input w-full" type="password" value={secret} maxLength={4096} autoComplete="new-password" onChange={e=>setSecret(e.target.value)} disabled={busy||!!pending}/></label>
      <label>Reply refresh token<input className="cockpit-input w-full" type="password" value={token} maxLength={8192} autoComplete="new-password" onChange={e=>setToken(e.target.value)} disabled={busy||!!pending}/></label>
      <label><input type="checkbox" checked={ack} onChange={e=>setAck(e.target.checked)} disabled={busy||!!pending}/> I separately consented to exactly these scopes and this identity profile.</label>
      <button className="cockpit-feedback-button" disabled={busy||!key||!!pending||!!error||!ack||!label||!clientId||!token}>Import separate reply profile</button>
    </form>
    {pending&&<div role="status">An import has an unconfirmed outcome; credentials are cleared and never stored in browser recovery state. <button className="cockpit-feedback-button" disabled={busy} onClick={()=>void run(reconcile)}>Inspect original import</button></div>}
    <div className="grid gap-2 mt-3"><label>Reply identity Goal<select value={goalId} onChange={e=>setGoalId(e.target.value)}><option value="">Choose current finite Goal</option>{goals.map(g=><option key={g.id} value={g.id}>{g.title} · revision {g.revision}</option>)}</select></label>
      <label>Identity readonly profile<select value={readId} onChange={e=>setReadId(e.target.value)}><option value="">Choose profile</option>{profiles.filter(p=>p.service==="gmail_reply_read"&&p.state==="active").map(p=><option key={p.connection_id} value={p.connection_id}>{p.label} · {p.scope_status}</option>)}</select></label>
      <label>Identity send profile<select value={sendId} onChange={e=>setSendId(e.target.value)}><option value="">Choose profile</option>{profiles.filter(p=>p.service==="gmail_reply_send"&&p.state==="active").map(p=><option key={p.connection_id} value={p.connection_id}>{p.label} · {p.scope_status}</option>)}</select></label>
      <button className="cockpit-feedback-button" disabled={busy||!!pairPending||!goal||!read||!send} onClick={()=>void run(async signal=>{const g=generation.current;const body={read_connection_id:readId,expected_read_revision:read!.revision,send_connection_id:sendId,expected_send_revision:send!.revision,goal_id:goal!.id,goal_revision:goal!.revision,acknowledge_identity_read:true,request_uuid:makeMailIdempotencyKey("reply-identity")};const raw=JSON.stringify(body);sessionStorage.setItem(key!+":identity",raw);if(sessionStorage.getItem(key!+":identity")!==raw)throw Error();setPairPending(body);const result=await pairReplyProfiles(body,signal);if(g===generation.current){setOutcome(result.outcome||result.status);sessionStorage.removeItem(key!+":identity");setPairPending(null);}await refresh(signal);})}>Verify same mailbox identity (up to 5 contacts)</button>
    </div>
    {pairPending&&<p role="status">Original identity verification retained; no automatic contacts. <button className="cockpit-feedback-button" disabled={busy} onClick={()=>void run(async(signal)=>{const g=generation.current;const result=await recoverReplyOperation("mail_reply_identity_v1",String(pairPending.request_uuid),signal);if(g!==generation.current)return;if(result){setOutcome(result.outcome||result.status);if(["succeeded","blocked","cancelled"].includes(result.status)){sessionStorage.removeItem(key!+":identity");setPairPending(null);}await refresh(signal);}else setOutcome("Original identity job is absent. Retry the exact original request explicitly.");})}>Inspect original identity verification</button><button className="cockpit-feedback-button" disabled={busy} onClick={()=>void run(async(signal)=>{const g=generation.current;const result=await pairReplyProfiles(pairPending,signal);if(g!==generation.current)return;setOutcome(result.outcome||result.status);sessionStorage.removeItem(key!+":identity");setPairPending(null);await refresh(signal);})}>Retry original identity request</button></p>}
    {profiles.map(p=><div className="mt-2 text-[10px]" key={p.connection_id}>{p.label} · {p.service} · {p.state} · {p.scope_status} <button className="cockpit-feedback-button" disabled={busy||p.state!=="active"} onClick={()=>void run(async signal=>{await revokeReplyProfile(p.connection_id,{expected_revision:p.revision,idempotency_key:makeMailIdempotencyKey("reply-revoke")},signal);await refresh(signal);})}>Revoke reply profile</button></div>)}
    {outcome&&<p role="status">{outcome}</p>}{error&&<p role="alert">{error}</p>}
  </section>;
}
