import { useEffect, useRef, useState } from "react";
import { API_URL } from "../../config/constants";
import { apiFetch } from "../../lib/api";
interface Pair {extension_id:string;reference:string;name:string;pairing:{device_id?:string;pairing_id?:string}}
export function SelectedContextPairing({ownerPrincipalId,ownerSessionId}:{ownerPrincipalId?:string|null;ownerSessionId?:string|null}){
  const [pairs,setPairs]=useState<Pair[]>([]),[selected,setSelected]=useState(""),[revision,setRevision]=useState(0),[ack,setAck]=useState(false),[current,setCurrent]=useState(""),[returned,setReturned]=useState(""),[locator,setLocator]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);const generation=useRef(0);
  useEffect(()=>{generation.current++;setBusy(false);setPairs([]);setSelected("");setAck(false);setCurrent("");setReturned("");setLocator("");return()=>{generation.current++;};},[ownerPrincipalId,ownerSessionId]);
  useEffect(()=>{const clear=()=>{setCurrent("");setReturned("");setLocator("");};window.addEventListener("blur",clear);return()=>window.removeEventListener("blur",clear);},[]);
  async function run(fn:(v:number)=>Promise<void>){if(busy||!ownerPrincipalId||!ownerSessionId)return;const v=generation.current;setBusy(true);setMessage("");try{await fn(v);}catch(e){if(v===generation.current){setReturned("");setMessage(e instanceof Error?e.message:"Pairing unavailable");}}finally{if(v===generation.current)setBusy(false);}}
  async function request(path:string,body?:unknown){const r=await apiFetch(`${API_URL}${path}`,{method:body?"POST":"GET",signal:AbortSignal.timeout(20000),...(body?{headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}:{})});const result=await r.json();if(!r.ok)throw Error(result.detail?.code??"Pairing unavailable");return result;}
  return <section aria-label="Optional selected text companion pairing"><h3>Optional selected text companion</h3><p>CPU Mac/Linux core requires no companion. Load companions/selected-text in Chromium only after reviewing the exact host permission. This pairing grants no Task execution; the Task inspector publishes a separate finite target and exact capture approval.</p>
    <button type="button" disabled={busy||!ownerPrincipalId} onClick={()=>void run(async v=>{const result=await request("/api/context/selected-text/pairings");if(v===generation.current){setPairs(result.pairings);setRevision(result.state_revision);setAck(false);}})}>Inspect existing device adapters</button>
    <select aria-label="Selected text adapter" value={selected} disabled={busy} onChange={e=>{setSelected(e.target.value);setAck(false);setReturned("");}}><option value="">Choose installed optional device adapter</option>{pairs.map((p,i)=><option key={p.reference} value={String(i)}>{p.name} · {p.pairing.device_id??"unpaired"}</option>)}</select>
    {!pairs.length&&<p>Adapter absent or not inspected: locally blocked. Install the existing optional device bridge from the extension catalog; no core service is required.</p>}
    <label>Existing credential for deliberate rotation<input type="password" autoComplete="off" value={current} onChange={e=>setCurrent(e.target.value)}/></label>
    <label><input type="checkbox" checked={ack} onChange={e=>setAck(e.target.checked)}/> Explicitly create or rotate this owned device credential. Legacy credentials are not automatically promoted.</label>
    <button type="button" disabled={busy||!ack||selected===""} onClick={()=>void run(async v=>{const p=pairs[Number(selected)];const rotate=!!p.pairing.device_id;if(rotate&&!current)throw Error("Current credential required for rotation");const result=await request(`/api/nodes/pairings/${rotate?"rotate":"pair"}`,{extension_id:p.extension_id,reference:p.reference,expected_revision:revision,...(rotate?{credential:current}:{}),reason:"Explicit selected-text companion pairing"});if(v===generation.current){setCurrent("");setAck(false);setRevision(result.revision);setReturned(result.credential);const entry=result.adapter.pairing;setLocator(JSON.stringify({extension_id:p.extension_id,reference:p.reference,name:p.name,device_id:entry.device_id,pairing_id:entry.pairing_id}));setMessage("Credential returned once. Manually enter these values in the trusted companion configuration. They are held only in this UI memory and clear on blur.");}})}>Create or rotate exact owned pairing</button>
    {returned&&<><label>Pair locator JSON<textarea readOnly value={locator}/></label><label>One-time pair credential<input readOnly type="password" value={returned}/></label><button type="button" onClick={()=>{setReturned("");setLocator("");}}>Clear returned credential</button></>}
    {message&&<p role="status">{message}</p>}
  </section>;
}
